Jacobian.lua

this allows one to use nn.Jacobian for float precision tests as well.

added optional precision parameter to nn.Jacobian

---

SparseLinear.lua
generic/SparseLinear.c

This gives insane speedup (if memory serves me right, 10-100x) for SparseLinear, thanks to Liang Xiong.
Tested and reviewed by @andresy

speedup and optimizations for SparseLinear

---

CMul.lua
doc/simple.md
test.lua

Hi,
This PR includes some CMul optimizations that make use of https://github.com/torch/cutorch/pull/93 and some older PRs. Augmented the unit tests. Allows more complex constructor arguments (like nn.Reshape), and updated the doc.

CMul optimizations, doc and unit tests

---

WeightedEuclidean.lua
test.lua

Some better unit tests and optimizations. Similar to #128 .

WeightedEuclidean optimizations

---

Euclidean.lua
test.lua

Includes unit tests. Optimized for the new non-contiguous copy kernels (https://github.com/torch/cutorch/pull/93).

Euclidean batch support

---

SpatialLPPooling.lua

Has to be a bit faster and cleaner. I also had a case when parameters of SubSampling changed during training with CUDA.

Simpler LPPooling with AveragePooling instead of SubSampling

---

MM.lua
doc/simple.md
init.lua
test.lua

Multiplies two matrices (or two batches of matrices).
This is a pure Lua implementation taking advantage of the new torch.bmm
function for minibatch inputs.

Matrix matrix multiplication layer.

---

L1Penalty.lua

`self.provideOutput` bug fixed.

L1Penalty bug fixed

---

MultiMarginCriterion.lua
doc/criterion.md
generic/MultiMarginCriterion.c
test.lua

This PR adds p=2 in:
```lua
loss(x,y) = forward(x,y) = sum_i(max(0, 1 - (x[y] - x[i]))^p) / x:size(1)
```
Also added test, cuda version is coming.

L2 MultiMarginCriterion

---

SpatialConvolution.lua

making SpatialConvolution use SpatialConvolutionMM ops at the backend

---

SpatialConvolution.lua

the new spatial conv is reverted to the traditional 4-dimensional weight layout (unlike MM), as this assumption is used all over the place in other modules that use SpatialConvolution inside them

keeping the traditional weight layout in the new SpatialConvolution

---

Module.lua
doc/module.md
test.lua

This PR includes doc and unit tests. The method has already been used for nn.Recurrent in nnx.

Module:listModules()

---

generic/SpatialAveragePooling.c
test.lua

Revert "Fixed SpatialAveragePooling - added division by filter size"

---

doc/simple.md

The output of the example was not correct.

Fixed nn.Reshape example with actual output

---

Power.lua

This is a PR that is a squashed version of https://github.com/torch/nn/pull/182 thanks to @rotmanmi

Now you can use power on inputs with 0s. (there is no longer division by 0)

---

View.lua
test.lua

fix special View case with -1 arg and dimension set <> 1

---

Linear.lua

Unused variable since f866103.

nn.Linear: remove unused variable

---

doc/convolution.md

This is hardly worth the time it took to make the PR :-)
Anyway, I just thought I would fix the SpatialBatchNormalization example code so that people don't get confused.

very small update to docs.

---

doc/simple.md

Reshape with the batch parameter makes people a little confused. This patch adds an example for it.

add example for reshape with mini-batch

---

Linear.lua

(this is especially helpful when using nngraph for doing reset inline).
Removed whitespace.

Return self on Linear.reset so it can be used inline.

---

CosineEmbeddingCriterion.lua
HingeEmbeddingCriterion.lua
L1HingeEmbeddingCriterion.lua
doc/criterion.md
doc/simple.md

This PR includes the following changes:
* Added doc for MultiLabelMarginCriterion (fixes #181)
* made the embedding criterion code breath a little better (small changes).
* moved the L1Penalty from criterion.md to simple.md (it is a module after all)
* Added an index to criterion.md (harmonizes it with the other markdowns)

Criterion doc++

---

SpatialConvolutionMM.lua

See https://github.com/torch/nn/issues/211

Fix for SpatialConvolutionMM cuda/cpu interoperability

---

SpatialDropout.lua
doc/simple.md
init.lua
test.lua

This is a super simple variation on Dropout that I have found empirically works better than dropout for fully-convolutional networks.  I explain about it in a little more detail here: http://arxiv.org/abs/1411.4280

Added SpatialDropout + doc + test.

---

Replicate.lua
doc/simple.md
test.lua

@soumith Here is a clean version of the previous pull request.
nn.Replicate now works across arbitrary dimensions.

Replicate now works across arbitrary dimensions.

---

JoinTable.lua
SelectTable.lua

Caught these bugs via travis. Bug was first introduced in #218

fixing small typecasting bugs in JoinTable and SelectTable

---

ReLU.lua
Threshold.lua
doc/transfer.md
generic/Sqrt.c
generic/Threshold.c

adds in-place ReLU and fixes a potential divide-by-zero in nn.Sqrt

---

BatchNormalization.lua
SpatialBatchNormalization.lua

now you can share them across models using :clone, because they are not lazy-initialized.

making running_mean/std shareable in batch normalization

---

View.lua
test.lua

now handles better -1 cases
i added yet another test case for this module.
better to try on your side, who knows?

fix View (hopefuly)

---

Sequential.lua

now nn.Sequential will support # operator - and who() will not crash

Sequential:__len() operator added

---

MarginRankingCriterion.lua
test.lua

MarginRankingCriterion:type()

---

ConcatTable.lua
Criterion.lua
CrossEntropyCriterion.lua
DotProduct.lua
L1HingeEmbeddingCriterion.lua
MarginRankingCriterion.lua
MixtureTable.lua
Module.lua
PairwiseDistance.lua
SpatialContrastiveNormalization.lua
SpatialDivisiveNormalization.lua
SpatialSubtractiveNormalization.lua
init.lua
utils.lua

Recursively iterate over the whole table, converting each tensor to the
given type. Removes need for many specialized type() functions.

Make type() truly recursive.

---

README.md
doc/criterion.md
doc/table.md

Added diagrams and cleaned the example code and documentation

Improving whole documentation

---

PReLU.lua

Buffer declaration for PReLU cuda implementation

Buffers for PReLU cuda implementation.

---

SpatialConvolution.lua

fixing https://github.com/torch/cunn/issues/87 using the same patch as from https://github.com/torch/nn/pull/214

fixing typing in SpatialConvolution

---

CriterionTable.lua
Euclidean.lua
MM.lua
MixtureTable.lua
Module.lua
View.lua
WeightedEuclidean.lua
doc/table.md
hessian.lua
test.lua

Torch7 defines table.unpack to unpack if it is not defined in PR https://github.com/torch/torch7/pull/225
Luajit 2.1.0 also defines table.unpack

Rename unpack to table.unpack for Lua 5.2

---

utils.lua

table.unpack fix

---

MixtureTable.lua
utils.lua

Also added `nn.utils.recursiveResizeAs`.

MixtureTable lazy initialized buffers

---

Dropout.lua
SpatialConvolution.lua
SpatialConvolutionMM.lua
SpatialDropout.lua
SpatialMaxPooling.lua

Adds:
- pbb in Dropout and SpatialDropout
- non default params in SpatialConvolution, SpatialConvonlutionMM, SpatialMaxPooling

Add more useful string description of layers.

---

ParallelCriterion.lua

cc: @nicholas-leonard 
In the build-up to fixing #272 I refactored the code a bit to shorten it.

refactor/cleanup of ParallelCriterion

---

Sequential.lua
doc/containers.md

There was no mention of `insert` it in the documentation and `remove` can be useful!

Document nn.Sequential.insert and add nn.Sequential.remove

---

SpatialDropout.lua

Just a small fix on error message.
`2D -> 3D`

small fix on error message

---

LookupTable.lua

should fix #319 , but cannot verify because do not have old serialized model.

backward compatibility for LookupTable

---

NarrowTable.lua
doc/table.md
init.lua
test.lua
utils.lua

nn.NarrowTable

---

JoinTable.lua

fixes jointable backward bug

---

CosineDistance.lua
doc/table.md
test.lua

I tried to keep backward compatibility with saved models.
Also, added a test, which was missing.

CosineDistance supports batch mode

---

MultiCriterion.lua
ParallelCriterion.lua
test.lua
utils.lua

[Parallel,Multi]Criterion table inputs

---

CAddTable.lua
CDivTable.lua
CMulTable.lua
CSubTable.lua

fixing table modules to return correct number of gradInputs

---

Sequential.lua

fixes https://github.com/torch/nn/issues/325

fixing Sequential.remove corner case

---

Mean.lua

Currently, `nn.Mean` is assuming contiguous gradOutput in its backward pass. Therefore, if, for example, two `nn.Mean` modules are chained, the backward pass will not produce correct gradients.
This minimal example can be used to reproduce the problem. This pr fixes it.
```lua
-- This script demonstrates that the non-contiguous output of nn.Mean():backward() leads
-- to backpropagation errors when it is fed into another nn.Mean():backward().
require 'nn'
-- Initialise data and backpropped gradient.
local data = torch.randn(3, 2, 7, 7)
local outGrad = torch.randn(3, 2)
-- Create a stack of two nn.Mean() layers.
local mod1a = nn.Mean(4)
local mod1b = nn.Mean(3)
-- Run fprop & bprop through the stack.
local resFwd1a = mod1a:forward(data)
local resFwd1b = mod1b:forward(resFwd1a)
local …
```

Fix contiguous gradoutput bug in nn.Mean

---

README.md
doc/containers.md
doc/convolution.md
doc/criterion.md
doc/index.md
doc/module.md
doc/overview.md
doc/simple.md
doc/table.md
doc/training.md
doc/transfer.md
mkdocs.yml

These changes will give you this : http://nn.readthedocs.org/en/readthedocs/index.html . Users will need to update dok as well.

nn.readthedocs.org

---

ClassNLLCriterion.lua
generic/ClassNLLCriterion.c
init.c

Moved ClassNLLCriterion to C. Normalization with weights is now done by the total weight of the minibatch, rather than its size

Improve ClassNLLCriterion

---

Dropout.lua
test.lua

reviewed internally at facebook

in-place dropout

---

ConcatTable.lua
test.lua

fixes test case in https://github.com/torch/nn/issues/332#issuecomment-126774117
added test case to unit tests

fixing bug in ConcatTable variable length

---

doc/table.md
doc/transfer.md

I was going through the documentation of the Transfer Function Layers. A few equations caught my eye. Please check.
- Amitrajit

minor documentation edit

---

test.lua

fixes https://github.com/torch/nn/issues/366

disabling hessian by default (as expected)

---

Module.lua

fixing cuda getparams

---

Module.lua

Revert "fixing cuda getparams"

---

SmoothL1Criterion.lua
doc/criterion.md
generic/SmoothL1Criterion.c
init.c
init.lua
test.lua

with a doc by @andreaskoepf from https://github.com/torch/nn/pull/374
CUDA PR is coming

Add C SmoothL1 criterion

---

generic/SparseLinear.c

As title suggests, this pull request offers a fast weight decay for SparseLinear.
One thing to note is that the new weight decay mechanism has different meaning than before. The new mechanism applies decay only if the input vector contains a value of the corresponding index, whereas previously weight decay is applied no matter what the input is. This may or may not be what you want, although I do think that it is not useful to apply weight decay for weights that are not indexed.
Note also that by default the .weightDecay member is 0, and the constructor does not set it. I read this as weightDecay is actually a hack in case one really needs it.

Fast weight decay for SparseLinear

---

SpatialConvolution.lua
SpatialConvolutionMM.lua

Fixes https://github.com/torch/nn/issues/415

Fix type() in SpatialConvolution

---

Normalize.lua

Revert "Fix modification of output in nn.Normalize"

---

Normalize.lua

This is the backwards-compatible version of #432

Fix modification of output in nn.Normalize (with lazy-loading of internal tensors)

---

doc/overview.md

Usually when training models with shared parameters, by reflex we share both the `parameters` and the `gradParameters` (if not, `optim` will complain about size mismatches).
But sharing the `gradParameters` while using an optimization procedure that iterates over the modules (like `updateParameters`, or even Facebook's `nn.Optim' I think) is wrong. See for example https://github.com/torch/nn/issues/395
Adding it to the docs to make it clearer.

Add note on training shared models

---

VolumetricDeconvolution.lua
doc/convolution.md
generic/VolumetricDeconvolution.c
init.c
init.lua
test.lua

Implemented by @dutran . Docs added by me.

adding VolumetricDeconvolution  + tests + doc

---

doc/criterion.md

Update the MarginCriterion's doc to follow the implementation introduced by 9176533

Update doc for MarginCriterion

---

Identity.lua

see: https://github.com/torch/nn/blob/master/doc/module.md#state-variables

State variable pointers should never change.

---

Identity.lua

Revert "State variable pointers should never change."

---

Max.lua
Mean.lua
Min.lua
doc/simple.md
test.lua

This completes https://github.com/torch/nn/pull/463 for nn.Mean, nn.Min and nn.Max

Add support for negative dimension and both batch and non batch inputs in nn.Min, nn.Max and nn.Mean

---

doc/criterion.md

Revert "Also clone grad weights and biases"

---

Cosine.lua
doc/simple.md
init.lua
test.lua

This PR adds a Euclidean-like module for measuring the cosine similarity between an input `x` and `k` cluster centers. Includes unit test and doc.

Cosine similarity

---

Cosine.lua

Fix for problem mentioned in https://github.com/torch/nn/pull/509/files#r46301793

Fix type() in Cosine

---

doc/table.md

the parameters of reshape() doesn't match input tensor

fix the bug in example

---

PairwiseDistance.lua

Output and gradInput should be initialized on use and not in constructor (as common in other modules), this allows proper sanitization.

PairwiseDistance sanitization-friendly

---

Concat.lua
Parallel.lua

the conditional expression is always false

fix a bug in conditional expression

---

MixtureTable.lua

fix a bug in assignment expression

---

MixtureTable.lua

some variables and expressions are useless

cancel unused variable and useless expression

---

PairwiseDistance.lua

error messages statements are redundant

the statements are redundant

---

MarginRankingCriterion.lua
doc/criterion.md
test.lua

Fixes https://github.com/torch/nn/issues/557
It seems that the batch version of this module was buggy since 2013 !

Fix batch mode in MarginRankingCriterion

---

generic/SpatialConvolutionMM.c

Better error message when number of input channels does not match the expected value

Improve error message in SpatialConvolutionMM

---

Module.lua

Revert "Don't re-flatten parameters if they are already flattened"

---

Dropout.lua

Dropout optimized for p == 0 not to perform any operations

Dropout optimized for p == 0

---

SpatialBatchNormalization.lua

didn't survive @colesbury's PR

fix batchnorm reset

---

CAddTable.lua

Revert "In-place option for CAddTable"

---

View.lua
doc/simple.md

adding :resetSize to nn.View

---

VolumetricMaxPooling.lua

serialization versioning and restoring the new field ceil_mode
tested locally.

back-compatibility of VolumetricMaxPooling

---

SelectTable.lua
test.lua

The bug can be created by running the updated unit test or also by running [rc1.lua here](https://github.com/sahiliitm/read-and-comprehend) (requires the rnn package)

Fixed SelectTable bug and added unit test

---

View.lua

print view size, eg:
```
nn.View(-1,2,20,28)
```

pretty tostring for nn.View

---

Mul.lua

fix for nn.Mul for cuda defaults

---

SpatialBatchNormalization.lua

forgot to add them in clearState.

clearState save_mean and save_std in BN

---

lib/THNN/generic/MultiLabelMarginCriterion.c
lib/THNN/generic/MultiMarginCriterion.c

Fix sizeAverage bug in MultiMarginCriterion (divide by nbatch, not ndim)

---

lib/THNN/generic/ClassNLLCriterion.c

adding a sanity check to ClassNLLCriterion

---

LookupTable.lua

allow non-contiguous gradOutput in LookupTable

---

ConcatTable.lua

Overrides backwards to recursively call backwards on child modules. Many other containers, such as `nn.Sequential` and `nn.Concat` already do this.
This makes it easier to share gradInput storages between modules of the same type to save memory.

Override Module:backwards in ConcatTable.

---

LookupTable.lua
THNN.lua
doc/convolution.md
lib/THNN/generic/LookupTable.c
lib/THNN/generic/THNN.h
test.lua

+ tests + doc
original author: Remi Lebret 
reviewer: @colesbury

adding paddingValue to LookupTable

---

MultiMarginCriterion.lua
THNN.lua
doc/criterion.md
lib/THNN/generic/MultiMarginCriterion.c
lib/THNN/generic/THNN.h
test.lua

Original Author: @adamlerer 
Reviewed By: @colesbury and me.

adding weights to MultiMarginCriterion

---

SparseLinear.lua

fixing back-compatibility of SparseLinear after https://github.com/torch/nn/pull/661#issuecomment-187815569

sparse linear back-compatibility fix

---

SparseLinear.lua
lib/THNN/generic/SparseLinear.c

Original author: Liang Xiong
Reviewed by: me and wickedfoo

sparselinear performance fixes

---

SpatialReflectionPadding.lua
SpatialReplicationPadding.lua
THNN.lua
doc/convolution.md
init.lua
lib/THNN/generic/SpatialReflectionPadding.c
lib/THNN/generic/SpatialReplicationPadding.c
lib/THNN/generic/THNN.h
lib/THNN/init.c
test.lua

+ docs + tests
Original author: Will Feng
Reviewed By: @wickedfoo and me

Adding SpatialReflection and SpatialReplication padding

---

Bilinear.lua
test.lua

Attempts to fix bug in nn.Bilinear's gradInput calculation: gradients wrt inputs are now weighted by gradOutput as expected.

updated gradInput calculation in Bilinear and added more tests

---

MultiMarginCriterion.lua
THNN.lua
doc/criterion.md
lib/THNN/generic/MultiMarginCriterion.c
lib/THNN/generic/THNN.h
test.lua

This is https://github.com/torch/nn/pull/637, but rebased and with updates to the docs.

Making margin parameterizable in nn.MultiMarginCriterion

---

lib/THNN/generic/SpatialConvolutionMM.c

Addresses https://github.com/torch/nn/issues/671

Add extra checks for convolution parameters

---

test.lua

Needed for https://github.com/torch/torch7/pull/562

Fix use of tester (should use asserteq for non-table values).

---

lib/THNN/generic/SparseLinear.c
test.lua

added a test that was much needed. removed an argcheck that broke batch mode.

add batch mode test for SparseLinear, fix a spurious check

---

test.lua

So one can reliably reproduce test results.

Add a seed argument for nn.test()

---

View.lua

Improve `nn.View()`'s `__tostring__()` method.

Fix __tostring()__ formatting

---

test.lua

fixes all warnings from recent tester refactor

---

MV.lua
init.lua
test.lua

Adding matrix vector multiplication in nn, following the conventions of nn.MM.

Adding nn.MV

---

Linear.lua

Calling addGradParameters with an input of different size than the input used for updateOutput resulted in an error previously. This is an issue for some efficient RNN implementations that merge updates together.
This change has no effect if Linear is used in the usual way, it only improves some corner cases.

Update addBuffer size in accGradParameters

---

ELU.lua
lib/THNN/generic/ELU.c
lib/THNN/generic/THNN.h
test.lua

Add an option to do ELU in-place, as can already be done with ReLU.

In-place ELU

---

SparseLinear.lua
lib/THNN/generic/SparseLinear.c
test.lua

indicies was defined to be global instead of local
Was getting the sparse row to zero instead of the sparse column.

Fixed Sparse Linear Bugs

---

doc/criterion.md

Revert "Formatted latex equations"

---

lib/THNN/generic/SpatialFullConvolutionMap.c

Fixes https://github.com/torch/nn/issues/521

Fix SpatialFullConvolutionMap non-contiguous bug

---

test.lua

As requested by @colesbury in #741

Add error handling test

---

SelectTable.lua
test.lua
utils.lua

Hi guys,
my last fix broke SelectTable. This fixes that.

SelectTable fix

---

doc/simple.md

fix typos in the doc for the module Unsqueeze

fix Unsqueeze doc

---

LookupTable.lua

See https://github.com/torch/nn/issues/675#issuecomment-210669866 for the motivation for this PR.
Also adds some more buffers to `clearState`
**Notes:**
As there is no constraint on the type of the input tensor to `LookupTable` (its data is copied to `self._input` if the type is not the right one), and as its more natural that `gradInput` and `input` have the same types, I allocate new tensors everytime the user changes the input type (and not the module type).
I'm not sure about this decision. Do you prefer to let `self.gradInput` to have the same type as `self.weight` ?
Let me know if you have remarks about those changes, as I have never used it I might be screwing up something.

Add dummy updateGradInput in LookupTable

---

MM.lua

fixes #781 
I am not super familiar with internals of Torch, so I hope this change does not cause unintended consequences.

fix MM after :clearState() has been called

---

MultiLabelMarginCriterion.lua
SelectTable.lua
Sum.lua
lib/THNN/generic/LogSoftMax.c
lib/THNN/generic/MultiLabelMarginCriterion.c
lib/THNN/generic/THNN.h

also, __tostring added in SelectTable, fixes for nn.Sum when gradOutput is not contiguous

MultiLabelMarginCriterion fixes for CUDA

---

lib/THNN/generic/SoftMax.c

Remove THExpMinusApprox from SoftMax

---

doc/simple.md

I've found this module useful, and thought it could be helpful to make it easier to find.

Add documentation for nn.Transpose

---

doc/training.md

Address https://github.com/torch/torch7/issues/684

replace the StochasticGradient example with optim example

---

lib/THNN/generic/LogSoftMax.c
test.lua

Fix for https://github.com/torch/nn/issues/832

logsoftmax non-contiguous gradOutput fix

---

SparseLinear.lua
lib/THNN/generic/SparseLinear.c
test.lua

Fixing sparse linear race condition

---

lib/THNN/generic/SparseLinear.c

Fixed memory leak introduced by https://github.com/torch/nn/pull/811/files

fix memory leak in SparseLinear

---

SpatialFullConvolution.lua
doc/convolution.md
lib/THNN/generic/SpatialFullConvolution.c
test.lua

Adds noBias for nn.SpatialFullConvolution

add noBias for nn.SpatialFullConvolution

---

Narrow.lua
Select.lua
test.lua

Adds negative dimension arguments to Select and Narrow.

Adds negative dim arguments to Select and Narrow

---

Bottle.lua
doc/containers.md
init.lua
test.lua

Slight improvement over https://github.com/torch/nn/pull/860

Implement Bottle container

---

BatchNormalization.lua
test.lua

adding non-minibatch mode for BatchNorm in evaluate mode

---

MarginRankingCriterion.lua
test.lua

fixes https://github.com/torch/nn/issues/813

fix batch=1 bug in MarginRankingCriterion

---

Index.lua
test.lua

succeeds https://github.com/torch/nn/pull/841

fixing clearState for Index

---

doc/convolution.md

modified:   doc/convolution.md

SpatialDilatedMaxPooling doc

---

Concat.lua
DepthConcat.lua
test.lua

size() is a method of the Container base class.
fixes #931

Don't overwrite self.size in Concat

---

Max.lua
Min.lua
Normalize.lua

fixes https://github.com/torch/cutorch/issues/468
cc: @szagoruyko @shuzi @jayleicn

fixing Max and Min for new cutorch types

---

SpatialConvolution.lua
lib/THNN/generic/SpatialConvolutionMM.c

This also requires merging torch/cunn#322

Accept both 2D and 4D weights in SpatialConvolutionMM

---

JoinTable.lua

fixes https://github.com/torch/nn/issues/920

fixing JoinTable bug for negative indices

---

SpatialDilatedMaxPooling.lua
SpatialMaxPooling.lua
lib/THNN/generic/SpatialDilatedMaxPooling.c
lib/THNN/generic/SpatialMaxPooling.c
lib/THNN/generic/THNN.h
lib/THNN/init.c

Addresses [this](https://github.com/torch/nn/pull/921#issuecomment-241229585)
modified:   SpatialDilatedMaxPooling.lua
modified:   SpatialMaxPooling.lua
renamed:    lib/THNN/generic/SpatialMaxPooling.c -> lib/THNN/generic/SpatialDilatedMaxPooling.c
modified:   lib/THNN/generic/SpatialMaxPooling.c
modified:   lib/THNN/generic/THNN.h
modified:   lib/THNN/init.c

Make SpatialMaxPooling API consistent

---

BCECriterion.lua
THNN.lua
lib/THNN/generic/BCECriterion.c
lib/THNN/generic/THNN.h
lib/THNN/init.c

Current implementation is very inefficient. Cuda is coming too.

BCECriterion THNN implementation

---

Module.lua

There's no need to serialize parameters that will be shared immediately
afterwards. In particular, the current implementation of clone and share is
inefficient for single modules in a larger network with flattened parameters
since the storage holding all parameters will be serialized.
Here, the write method of nn.Module is temporarily overwritten with a function
that writes empty tensors for all shared parameters.

Don't serialize shared parameters in clone()

---

Concat.lua
ConcatTable.lua
Parallel.lua
ParallelTable.lua

Bug fix (missing `#` in table containers)
Improve visualisation (remove `|` from last entry), based on https://github.com/Atcold/torch-pretty-nn/pull/1.

Remove extra | and bug fix ConcatTable

---

ClassNLLCriterion.lua
SpatialClassNLLCriterion.lua

making ClassNLLCriterion targets consistent between cpu and cuda

---

doc/simple.md

Add() Make it clear that inputDimension is optional

---

doc/transfer.md

Hold on on merging, I'm taking this to my *Vim*. It's impossible to fix it from *GitHub* without going insane.

Updating non-linear functions

---

LookupTable.lua
Max.lua
Min.lua
Normalize.lua

This extends https://github.com/torch/nn/pull/979

More broken compatibility with cutorch 1.0

---

ClassNLLCriterion.lua
SpatialClassNLLCriterion.lua

There was a problem when giving a `CudaTensor` input and a `CudaLongTensor` target. The target was then converted to `long`.

 ClassNLLCriterion bad cast

---

lib/THNN/CMakeLists.txt
lib/THNN/generic/BatchNormalization.c
lib/THNN/generic/HardTanh.c
lib/THNN/generic/LogSoftMax.c
lib/THNN/generic/LookupTable.c
lib/THNN/generic/SoftMax.c
lib/THNN/init.c

Hi,
This minor change is for nn on windows, all tests passed.
Thanks,

change to work on windows && replace long with ptrdiff_t

---

Linear.lua
lib/THNN/generic/Linear.c
lib/THNN/generic/THNN.h
lib/THNN/init.c
test.lua
test/LinearTHNN.lua

This PR implements a port of `Linear.lua` to `THNN`.
I have tried to keep the implementation as close as possible to the original code and to adopt a coding style that fits `THNN`.
All tests in `test.lua` pass.

Ported Linear module to THNN

---

lib/THNN/generic/SpatialMaxUnpooling.c
lib/THNN/generic/VolumetricMaxUnpooling.c

Even though these functions have bounds checks they segfault sometimes for invalid indices. It's probably because of calling `longjmp` in `THError`, while still being inside an OpenMP loop - according to the specs the parallel region has to execute completely (even `break` is illegal).

Don't jongjmp out of omp loops in unpooling modules

---

Concat.lua

1) added support for tables as inputs to Concat, 
2) removed some code redundancy (similar to ConcatTable)

added support for tables as inputs to Concat

---

lib/THNN/generic/SpatialDilatedConvolution.c
lib/THNN/generic/SpatialDilatedMaxPooling.c

in SpatialDilatedConvolution and SpatialDilatedMaxPooling.

Fix checking and spacing of dilation parameters

---

PairwiseDistance.lua

By default using Euclidean/l2 distance/norm.

PairwiseDistance: Default using Euclidean distance.

---

Narrow.lua
doc/simple.md
test.lua

Original internal PR by Angela Fan ( @huihuifan )

Support negative offset in nn.Narrow

---

lib/THNN/generic/SpatialMaxUnpooling.c
lib/THNN/generic/VolumetricMaxUnpooling.c

These modules behaved weird whenever THError triggering inputs were given.

fixing OpenMP longjmp bugs in *MaxUnpooling

---

lib/THNN/generic/SpatialAveragePooling.c

input is unused in SpatialAveragePooling_updateGradInput

Remove unused buffer in avg pooling

---

GatedLinearUnit.lua
doc/transfer.md
init.lua
test.lua

added nn layer gated linear unit, associated unit tests, documentation modification

adding gated linear unit and tests to nn

---

DistanceRatioCriterion.lua
doc/criterion.md
init.lua
test.lua

Rebased and cleaned up https://github.com/torch/nn/pull/1044

Initial Commit for DistanceRatioCriterion for triplet siamese model training

---

THNN.lua
lib/THNN/generic/ELU.c
lib/THNN/generic/HardShrink.c
lib/THNN/generic/HardTanh.c
lib/THNN/generic/LeakyReLU.c
lib/THNN/generic/Linear.c
lib/THNN/generic/LookupTable.c
lib/THNN/generic/MarginCriterion.c
lib/THNN/generic/MultiMarginCriterion.c
lib/THNN/generic/PReLU.c
lib/THNN/generic/RReLU.c
lib/THNN/generic/SoftPlus.c
lib/THNN/generic/SoftShrink.c
lib/THNN/generic/SparseLinear.c
lib/THNN/generic/SpatialConvolutionLocal.c
lib/THNN/generic/SpatialConvolutionMM.c
lib/THNN/generic/SpatialConvolutionMap.c
lib/THNN/generic/SpatialDilatedConvolution.c
lib/THNN/generic/SpatialFullConvolution.c
lib/THNN/generic/SpatialFullConvolutionMap.c
lib/THNN/generic/SpatialSubSampling.c
lib/THNN/generic/Sqrt.c
lib/THNN/generic/THNN.h
lib/THNN/generic/TemporalConvolution.c
lib/THNN/generic/TemporalSubSampling.c
lib/THNN/generic/Threshold.c
lib/THNN/generic/VolumetricConvolution.c
lib/THNN/generic/VolumetricConvolutionMM.c
lib/THNN/generic/VolumetricDilatedConvolution.c
lib/THNN/generic/VolumetricFullConvolution.c

This is done to be consistent with the changes made to cunn

Using accreal instead of real in the API

---

MapTable.lua

Fixes Issue #1141: https://github.com/torch/nn/issues/1141

Fix memory issue with MapTable module removal

---

WeightNorm.lua
doc/containers.md
init.lua
test.lua

adding container, documentation, and tests (also tested on modules in fbnn). 
let me know if I should revert the whitespace changes in containers.md.

adding weight norm container

---

lib/THNN/generic/TemporalRowConvolution.c
lib/THNN/generic/VolumetricConvolutionMM.c
lib/THNN/generic/unfold.c

needed for https://github.com/torch/torch7/pull/944

THVector_(add) -> THVector_(adds)

---

Contiguous.lua
test.lua

Fix for https://github.com/torch/nn/issues/1160

Fix and test case for nn.Contiguous

---

doc/convolution.md

Update doc for SpatialBatchNormalization

---

lib/THNN/generic/Linear.c
lib/THNN/generic/SpatialConvolutionLocal.c
lib/THNN/generic/SpatialConvolutionMM.c
lib/THNN/generic/TemporalConvolution.c
lib/THNN/generic/TemporalRowConvolution.c
lib/THNN/generic/VolumetricConvolutionMM.c

Using temporary variables when performing transpose + addmm

---

WeightNorm.lua

In evaluation mode, it's not necessary to re-compute the child module's weights
at every forward pass. Instead, do it once when switching from training to
evaluation mode. This speeds up inference.

WeightNorm: don't update weights when not in training mode

---

Bottle.lua
Decorator.lua
DontCast.lua
NaN.lua
Profile.lua
README.md
WeightNorm.lua
doc/containers.md
init.lua
rocks/nn-scm-1.rockspec
test.lua

This PR includes the following:
* the abstract `Decorator` module;
* makes `Bottle` and `WeightNorm` inherit `Decorator`
* adds the following decorator subclasses (from dpnn):
*  `NaN` for debugging NaN errors
* `Profile` for profiling modules
* `DontCast`for preventing modules from being cast
* unit tests 
* documentation
* adds 'moses' as a dependency in the rockspec (will need to update torch/rocks) in a different PR

Decorator modules

---

ClassNLLCriterion.lua
doc/criterion.md
lib/THNN/generic/ClassNLLCriterion.c
lib/THNN/generic/THNN.h
test.lua

@soumith let me know if this is what you had in mind.

ClassNLLCriterion supports missing targets

---

ClassNLLCriterion.lua
doc/criterion.md
lib/THNN/generic/ClassNLLCriterion.c
lib/THNN/generic/THNN.h
test.lua

Reverts torch/nn#1215
Right now nn and cunn are broken wrt each other.
I'll remerge this PR once @nicholas-leonard sends his cunn changes.

Revert "ClassNLLCriterion supports missing targets"

---

lib/THNN/generic/SpatialDepthWiseConvolution.c

Calling :noBias() on nn.SpatialDepthWiseConvolution results in segfaults during both forward and backward passes. PR fixes the issue.

Fix segfault in SpatialDepthWiseConvolution w/o bias

---

FeatureLPPooling.lua
init.lua
lib/THNN/generic/FeatureLPPooling.c
lib/THNN/generic/THNN.h
lib/THNN/init.c
test.lua

This is a naive CPU implementation of L_p feature pooling to correspond with
https://github.com/torch/cunn/pull/477
includes the original test from fbcunn that it passes.

CPU implementation of L_p feature pooling
