- Concat.lua
- Container.lua
- Parallel.lua
- Sequential.lua
- init.lua
- test.lua
nn.Container helps simplify the code for all of the container modules like nn.Parallel, nn.Concat, nn.Sequential etc.
This PR introduces nn.Container, and makes some of the existing container modules make it as the base class.
This change is fully backward-compatible in terms of serialization.
Reviewed by @andresy, authored by Keith Adams
> refactoring all the common container code into nn.Container

- Concat.lua
- ConcatTable.lua
- Container.lua
- Parallel.lua
- ParallelTable.lua
- doc/containers.md
- test.lua
This PR adds a couple of things:
* fixes the Parallel:updateOutput where self.module[i]:updateOutput(input) was being called twice...
* added unit tests for Parallel and ParallelTable
* ParalleTable and ConcatTable now inherit nn.Container
* added nn.Container doc
* the containers now call torch.type(self) to get a string representation of their name, which facilitates inheritance
> Parallel, Container & cie

- Copy.lua
- doc/simple.md
- test.lua
Hi,
This PR adds two optional arguments to nn.Copy (see doc for explanation). Also adds a nn.Copy unit test.
> new Copy constructor arguments

- MM.lua
The CudaTensor.bmm expects the output to be already a 3D tensor.
> Resized nn.MM output to support CudaTensors.

- CosineEmbeddingCriterion.lua
- test.lua
For negative pairs (`y == - 1`) the margin was NOT taken into account when computing the gradients.
In other words `updateGradInput` did return non zero gradients when the cosine similarity was below the margin (e.g this is not the case with [L1HingeEmbeddingCriterion](https://github.com/torch/nn/blob/822a742/L1HingeEmbeddingCriterion.lua#L33-L35) which behaves properly).
I have included a tiny non regression test.
> CosineEmbeddingCriterion: zero grads below margin

- generic/VolumetricMaxPooling.c
- test.lua
Resolves #171.
Note: Torch Tensor does not offer a resize6d function, which is necessary for batch mode. I replaced that with the generic tensor resize function for now. This requires an additional free() call.
> Add batch mode for VolumetricMaxPooling

- generic/SpatialAveragePooling.c
- test.lua
SpatialAveragePooling layer only summed the filters without dividing by filter size, the following code failed:
```lua
require 'nn'
require 'cudnn'
a = torch.rand(1,1,2,2):fill(1)
l = nn.SpatialAveragePooling(2,2)
b = l:forward(a)
a2 = torch.rand(1,1,2,2):fill(1):cuda()
l2 = cudnn.SpatialAveragePooling(2,2):cuda()
b2 = l:forward(a)
assert(b==b2)
```
Fixed both forward and backward.
> Fixed SpatialAveragePooling - added division by filter size

- SpatialAveragePooling.lua
- SpatialLPPooling.lua
- generic/SpatialAveragePooling.c
- test.lua
Fixes https://github.com/torch/nn/pull/178  with compatibility with saved models
Note: cudnn, ccn2, imagine-nn are dividing by kW*kH
Also had to fix SpatialLPPooling
> SpatialAveragePooling divides by kW*kH

- Module.lua
These 2 calls of collectgarbage() can save a large chunk of temporary memory when calling getParameters(). It is particularly useful when working with GPUs on a model with large number of parameters, for which it would otherwise be impossible to even call getParameters() (out of memory cuda error).
> Added 2 calls to collect garbage for getParameters

- generic/SpatialConvolutionMM.c
I guess the variable 'gradOutputPlane'  is floating around and not used in any nn/cunn package. So removed from the routine.
> Remove an unused variable from ConvMM

- Linear.lua
This PR fixes a bug where the Linear.addBuffer is empty. This happens when using some of the torch-utils tools where non parameter buffers are resized to zero when saved to disk, and then reloaded. 
Not sure this is a good reason to make the PR, but in any case, it fixes the bug.
> empty addBuffer fix

- SpatialConvolution.lua
This removes the dependency of updateOutput on gradWeight for SpatialConvolution. In production code, this is a plus (and sometimes a must).
> Spatial convolution fix

- SelectTable.lua
Model:type() is overriden:
```Lua
function SelectTable:type(type)
self.gradInput = {}
end
```
However, SelectTable has other fields: output and _type, which should be changed by this function.
Proposed fix: add `return parent.type(self,type)` before the end of the function.
`parent:type(type)` doesn't work, because the `self` that is used in this call does not contain the attributes of SelectTable.
`return` has been added because it is done like this in the other :type() functions.
> SelectTable:type() must call Model:type()

- generic/SpatialConvolutionMM.c
There is a bug in SpatialConvolutionMM when using padding and convolving tensors with filters which are larger than the input. For example, the following snippet produces a segfault:
```
require 'nn'
M = nn.SpatialConvolutionMM(4,4,5,5,1,1,2)
T = torch.Tensor(4,1,1):zero()
print(M(T))
```
My assumption is that the code on lines 104-110 should produce the same result as lines 96-101 when dW=1. Therefore the fix.
> SpatialConvolutionMM: fixed corruption on small padded tensors

- generic/SpatialAdaptiveMaxPooling.c
- test.lua
This PR removes the memory copy when the input tensors are non-contiguous. This is specially useful when forwarding inputs tensors cropped with `:sub`.
> Adding strides in SpatialAdaptiveMaxPooling to avoid copies on non-contiguous input tensors

- AddConstant.lua
- MulConstant.lua
- doc/transfer.md
- test.lua
Additionally, it also restores the initial value of the input in its backward pass, allowing it to be used after other in-place modules.
For example,
```lua
m = nn.Sequential()
m:add(nn.AddConstant(5,true)):add(nn.MulConstant(2,true)):add(nn.AddConstant(1,true))
```
works as its out-place equivalent, for both forward and backward functions.
> Adding in-place AddConstant and MulConstant

- Module.lua
Also:
* Tidied up some whitespace.
* Replaced a legacy check with the newer torch.isTensor()
> Nicer error message when flattening parameters with inconsistent types.

- Concat.lua
- DepthConcat.lua
- Sequential.lua
This adds :backward to the three containers Concat, DepthConcat and Sequential.
If a module has a more efficient one-step :backward rather than updateGradInput + accGradParameters separately, then this will help the module.
The PR is open for comment, @andresy approved it already.
> adding direct :backward to Concat, DepthConcat, Sequential

- ClassNLLCriterion.lua
Corrects fprop in ConcatTable when model was saved with nilling (replacing all outputs with empyTensor)
corrects the behavior of who() in presence of ClassNLLCriterion
(I do not have trepl in my Windows installation)
> small improvements in ConcatTable and ClassNLLCriterion

- MultiCriterion.lua
- ParallelCriterion.lua
- doc/criterion.md
- init.lua
- test.lua
This PR adds the ParallelCriterion (formerly [SuperCriterion](https://github.com/clementfarabet/lua---nnx/blob/master/SuperCriterion.lua)). It includes unit tests and doc. It also includes unit tests for the related MultiCriterion and some doc to differentiate the two. I changed the name to make it more consistent with the naming convention of Modules.
> ParallelCriterion

- SpatialConvolution.lua
Small fix to help SpatialConvolution handle empty gradParams (for production models).
> SpatialConvolution empty gradParams fix

- Replicate.lua
- SpatialDivisiveNormalization.lua
- SpatialSubtractiveNormalization.lua
- doc/simple.md
- test.lua
This PR adds batch mode for SpatialContrastiveNormalization, SpatialDivisiveNormalization, SpatialSubtractiveNormalization and Replicate. Includes unit tests and doc.
Test command:
```lua
th -lnn -e "nn.test{'SpatialDivisiveNormalization_2dkernel','Replicate','SpatialDivisiveNormalization_1dkernel','SpatialSubtractiveNormalization_2dkernel','SpatialSubtractiveNormalization_1dkernel','SpatialContrastiveNormalization'}"
Running 6 tests	
______  ==> Done Completed 44 asserts in 6 tests with 0 errors	
--------------------------------------------------------------------------------	
```
> Batch Mode

- Linear.lua
removes "fill" calls because they can be done in blas. gives nice speedup for small matrices on CUDA, doesn't hurt cpu.
> moved zeroing to blas side in batch nn.Linear:forward

- Linear.lua
As addmm was fixed the special case in Linear is not needed (was added here https://github.com/torch/nn/pull/25). There is a negligible numerical difference with CUBLAS between the general and special case.
> Removed special case for nunit = 1 in Linear

- SpatialAveragePooling.lua
- SpatialConvolution.lua
- SpatialConvolutionMM.lua
- SpatialMaxPooling.lua
As discussed with @Atcold tostrings look like this:
```
nn.Sequential {
[input -> (1) -> (2) -> (3) -> (4) -> (5) -> (6) -> (7) -> (8) -> (9) -> (10) -> output]
(1): nn.SpatialConvolution(2 -> 96, 7x7, 3,3)
(2): nn.ReLU
(3): nn.SpatialMaxPooling(2,2,2,2)
(4): nn.SpatialConvolution(96 -> 192, 5x5)
(5): nn.ReLU
(6): nn.SpatialMaxPooling(2,2,2,2)
(7): nn.SpatialConvolution(192 -> 256, 3x3)
(8): nn.ReLU
(9): nn.View
(10): nn.Linear(256 -> 1)
}
```
Also fixes https://github.com/torch/nn/issues/279 and adds similar tostring to average pooling
> Less cluttering tostring

- BatchNormalization.lua
- SpatialBatchNormalization.lua
- doc/convolution.md
- doc/simple.md
- test.lua
fixing batchnorm tests
fixes https://github.com/torch/nn/issues/282
> batchnorm is clonable by adding the running estimates to constructor

- generic/SparseLinear.c
This fixes the `omp_get_thread_num` implicit declaration warning.
> SparseLinear.c: fix missing OpenMP include

- LookupTable.lua
- generic/LookupTable.c
- init.c
Adds an efficient CPU implementation of LookupTable. The forward and
backward passes are implemented in C, which makes it easier to add
an efficient CUDA implementation in cunn.
I've added a benchmark here:
https://gist.github.com/colesbury/442c3b6f1ac73cf52036
Thanks to David Grangier for the FasterLookupTable on which it's based.
> Speed up LookupTable

- Container.lua
The train attribute of containers should also be set to true or false (not just non-container modules).
> set self.train=[true,false] for containers

- SpatialConvolution.lua
- SpatialConvolutionMM.lua
- doc/convolution.md
- generic/SpatialConvolutionMM.c
- test.lua
This commit allows different paddings for each spatial dimension.
A PR with the Cuda version will come tomorrow.
I changed the print function a bit, as it was calling a `self.pad_h` and `self.pad_w` that, to the best of my knowledge, didn't exist anywhere (`cudnn` uses `padH` and `padW`). I think though that the current print version is ambiguous when `pad !=0` and `dW=dH=1`, or `pad=0` and `dW!=1 or dH!=1`, but I decided not to change it in this commit.
> SpatialConvolutionMM supports padW/padH != 1

- LookupTable.lua
Incremented the version attribute for the major changes introduced in the last PR related to this module. And makes the input contiguous once in updateOutput, instead of both updateOutput and accGradParameters. Unit tests pass.
> LookupTable makeInputContiguous only once

- SpatialConvolution.lua
- SpatialConvolutionMM.lua
- test.lua
@szagoruyko pointed that sometimes the tests for `SpatialConvolutionMM` were failing, with error
`SpatialConvolutionMM$ Error: matrices expected, got 2D, 1D tensors at /opt/rocks/torch7/lib/TH/generic/THTensorMath.c:594`.
There was an inversion of the dimensions while defining the non-contiguous tensor, thus some tests fed invalid input sizes.
Do you think we should we assert that proper-sized input tensors are given to the forward pass ?
Plus, small fix in the `__tostring__` methods.
> Fix print and correct non-contiguous test in SpatialConvolutionMM

- LookupTable.lua
The CUDA version of LookupTable was incorrect for 2D inputs. This fixes
it by viewing 2D inputs as a 1D tensor.
> Fix CUDA LookupTable with 2D inputs.

- SpatialConvolution.lua
- SpatialConvolutionMM.lua
Another small fix to SpatialConvolution(MM) tostring. If strides were equal to 1 it would print paddings in place of strides which is confusing.
> Fixes print SpatialConvolution paddings when strides are 1

- SplitTable.lua
- doc/table.md
- test.lua
This module can now be used when the total number of dimensions is unknown.
> Add support for negative indices in nn.SplitTable

- Narrow.lua
Is this reasonable? We have a use case where we need to accept LongTensors as inputs.
> Allowing Narrow to be agnostic to input type.

- Module.lua
I think this code should have been removed in 50de1a9.
This is causing access to undeclared global variable (when running with `-g` flag) and could have some side effect if these globals are already used.
> Remove unused code in nn.Module

- SpatialMaxPooling.lua
- doc/convolution.md
- generic/SpatialMaxPooling.c
- test.lua
- Adds padding
- adds ceil mode similar to `cudnn`, allowing `loadcaffe` to run on CPU
- changes the way the max indexes are stored, saving memory and computation time. For huge tensors we could have problems in the backward pass though, as we are storing the indices in a `Tensor` and not `LongTensor`.
@szagoruyko is preparing a PR for `cunn` with the same changes.
> SpatialMaxPooling supports padding and ceil mode

- Jacobian.lua
- Module.lua
- hessian.lua
- test.lua
This PR adds unit tests for the Hessian code and fixes several bugs found during testing:
1. Fix initialization of `diagHessianBias` for `nn.SpatialConvolution`.
2. Fix computing `diagHessianBias` for `nn.SpatialFullConvolution`.
3. Call `module:forward()` with the proper input before calling `accGradParameters()`.
Without that, `accDiagHessianParameters()` produces incorrect results for several convolution classes, which leads to weird bugs like this: https://github.com/koraykv/unsup/issues/30#issuecomment-112900751
4. Factor out duplicate code from `Module.getParameters()`.
The replacement `Module.getParameters()` function in `hessian.lua` containes a chunk of outdated code copied from `Module.lua` three years ago. This code has not been kept in sync with original code in `Module.lua` …
> Add unit tests for hessian.lua, fix bugs detected by the tests

- SelectTable.lua
If you give a larger input, and then give a smaller input next, the gradInput will have artifacts from the previous backward.
> Fix SelectTable variable input size bug

- HingeEmbeddingCriterion.lua
- doc/criterion.md
- test.lua
Rewrote HingeEmbeddingCriterion to support batch mode. Is compatible with the original version (accepting non-tensor y as well).
> HingeEmbeddingCriterion: batch mode

- utils.lua
Tensor of 3 dims can have a 4th singleton dimension added. The assertion was wrong but the rest of the code is correct. cc: @dominikgrewe
> fixing corner-case of last dimension in addSingletonDimension

- Module.lua
This is a minor fix. The reference to the local `Module` variable creates an unnecessary upvalue which can make serialization more troublesome.
> Replace Module.flatten by nn.Module.flatten

- Padding.lua
nn.Padding was broken: input was returned in backprop instead of gradInput. Pitty that the test didn't catch it.
> fixed nn.Padding

- Linear.lua
This fixes https://github.com/torch/nn/commit/8abe926769258b63ec0938f35d85a58960f01425
> Forcing zeroing when self.output is resized (nn.Linear)

- doc/convolution.md
The SpatialBatchNormalizationExample does not evaluate, as the colon operator is not used (model.forward is rather than model:forward).
> Fix SpatialBatchNormalization documentation example.

- CosineEmbeddingCriterion.lua
- doc/criterion.md
- test.lua
Extends `CosineEmbedidingCriterion` to support batch mode. A few remarks
* I couldn't avoid memory allocation in https://github.com/torch/nn/compare/master...fmassa:cosine_embed_batch?expand=1#diff-d0f98c4047e236a26fe4f983397e0e15R63 and https://github.com/torch/nn/compare/master...fmassa:cosine_embed_batch?expand=1#diff-d0f98c4047e236a26fe4f983397e0e15R65
* added a slightly modified version of `criterionJacobianTest1DTable` for `table` inputs
> CosineEmbeddingCriterion supports batch mode

- Module.lua
- test.lua
This was meant to reduce temp buffer use when calling getParameters on a cunn model.
The old code uses 2x temporary buffer space. This code reduces it to 1x, and adds a hook so you can construct that buffer on the CPU rather than the GPU.
While rewriting this function, I also found a couple pretty severe bugs. Basically, if you have a non-compact parameter tensor (i.e. non-contiguous even after transpose), then the tensor will now point into unallocated memory. You can't completely fix that bug, because in some cases there's no way to "compact" the parameters while still having constant strides. So I have to just assert against that case.
> getParameters: improve memory use, fix bug with non-compact tensors

- CMul.lua
- Copy.lua
- Criterion.lua
- Euclidean.lua
- FlattenTable.lua
- JoinTable.lua
- LookupTable.lua
- MixtureTable.lua
- Module.lua
- ParallelCriterion.lua
- SelectTable.lua
- WeightedEuclidean.lua
- doc/module.md
- test.lua
- utils.lua
This PR contains two features:
1) Preserve sharing semantics when typecasting a network (https://github.com/torch/nn/issues/187). Shared references to tensors, as well as tensors sharing the same underlying storage, are preserved. 
The new :type() function typecasts the entire storage rather than just the tensor view, so it's possible to waste memory if you typecast a tensor that's a view on a small part of a much larger storage. Suggestions welcome.
2) Add `nn.Module:apply()` function similar to nngraph. (nngraph's `gModule:apply()` will be subsumed by `nn.Module:apply()`).
> nn.Module preserve type sharing semantics (#187); add nn.Module.apply

- SparseLinear.lua
Is there any reason not to do this in the current code? The special SparseLinear_updateParameters function is implemented in C but SparseLinear.updateParameters still points to Module.updateParameters. Let me know if there is some purpose I did not see.
> Using the speed-up version of updateParameters for SparseLinear

- test.lua
Both `output` and `outputc` pointed to the same tensor (`module.output`), so the tests would never fail. Same for `gradInput`.
> Fix non-contiguous test in SpatialConvolutionMM

- SpatialBatchNormalization.lua
Super-minor change. Not initialising those variables saved 30% of GPU memory when not training.
> Minor change for memory saving

- Normalize.lua
- doc/simple.md
- init.lua
- test.lua
Generalizes https://github.com/torch/nn/pull/260 from @karpathy to accept arbitrary `L_p` norms.
A few remarks:
* Maybe `LpNormalize` or `Normalize` is a better name ?
* Only accepts 1D/2D inputs. @nicholas-leonard proposed to add a `dim` parameter to make it equivalent to `torch.norm`. Is it worth it given that we have `SpatialBatchNormalization` ?
* `updateGradInput` is quite memory consuming for large `d`.
cc: @bamos
> Adds nn.Normalize

- ClassNLLCriterion.lua
`total_weight_tensor` becomes to have a meaningful number after loss:forward(). Calling loss:backward() without loss:forward() will end up with zero output https://github.com/torch/nn/commit/ef2e3d290418c411add8eee8dd5ca7d486362ad8#diff-e3ab2ae1e4ca35f9a37e0702421d52ffR97. This commit considers the case.
> Set default value of total weight in ClassNLL to 1

- BCECriterion.lua
- doc/criterion.md
- test.lua
Author: Armand Joulin
Rewriting the BCECriterion. The goal is to make it clearer and to have the possibility to weight the different terms.
New features:
- can use weights
- use less memory during forward (3 times less) and backward (2 times less).
- slightly faster forward and backward on both gpu and cpu
> BCECriterion rewrite

- SpatialSoftMax.lua
- doc/transfer.md
- generic/SoftMax.c
- init.lua
- test.lua
The module applies softmax in space and works both on a single
vector/matrix (1D/2D) or spatial vector/matrix (3D/4D).
> Update SoftMax to work in spatial mode

- doc/criterion.md
As per https://github.com/torch/optim/issues/73, gradWeight and gradBias should also be cloned.
> Also clone grad weights and biases

- generic/Abs.c
- generic/Sqrt.c
- generic/Tanh.c
> THTensor_(*) for abs, sqrt and tanh

- BCECriterion.lua
Found a bug in the new `BCECriterion`. The `updateOutput` method returns `NaN`
instead of zero when prediction is correct. The bug affects `FloatTensor` and
`CudaTensor`, but not `Tensor`.
require 'torch'
require 'nn'
y = torch.FloatTensor{1, 0}
t = torch.FloatTensor{1, 0}
crit = nn.BCECriterion():float()
-- returns nan, expected 0
print(crit:forward(y, t))
The problem was that `eps` was handled incorrectly. Concretely,
x:add(1 + eps)
is not the same as
x:add(1):add(eps).
The first example just adds one when `x` is `FloatTensor` or `CudaTensor`.
> Add eps correctly

- Linear.lua
Remove a `new()` that introduces lots of spurious mallocs when the input tensor size is not constant.
> Remove spurious mallocs from nn.Linear

- BCECriterion.lua
When using `weights` with 2D `targets`, `:size()` is unnecessarily called, allocating a new tensor at every `:forward` and `:backward`.
> Remove unnecessary mallocs from BCECriterion

- doc/simple.md
There is currently no module named `CDiv` in `nn`.
Maybe there were plans to add it but then it was forgotten ? Anyway, seems to be redundant given that we have `CMul`, and also more unstable than multiplications (divisions by zero and huge effects on output by varying a bit the weights)
Refers to https://github.com/torch/nn/issues/418
> Remove CDiv from doc

- GradientReversal.lua
- doc/simple.md
- init.lua
- test.lua
Implemented a GradientReversal layer, as seen in [Domain-Adversarial Training of Neural Networks](http://arxiv.org/abs/1505.07818) (though quite possibly not its first appearance). Can be used to maximise a loss function with gradient descent, especially in tandem with minimising other loss functions normally.
Also did a little tidying up of the docs.
> Add GradientReversal layer

- Normalize.lua
It's almost 40x faster on CPU, and doesn't use extra memory. Should
be faster on GPU as well, but I haven't benchmarked.
* Instead of creating a temporary matrix `b1*b2` of size `(n,d,d)`, rearrange the computations to avoid creating this huge matrix which was eating all the memory.
* `forward` and `backward` supports varying dimensionality (which wasn't the case before because of the `eye` matrix)
Should be of interest to @ffmpbgrnn and @bamos.
> Speedup and reduce memory usage in Normalize

- Container.lua
Adding :applyToModules() to nn.Container, which is like :apply() but only applies the given function to the submodules, not itself.
> Adding :applyToModules() to nn.Container, which is like :apply() but does not apply the function to itself.

- MulConstant.lua
Change suggested by Natalia Gimelshein
To align behaviour on other modules ([linear](https://github.com/torch/nn/blob/master/Linear.lua#L60), [spatial convolution](https://github.com/torch/nn/blob/master/Linear.lua#L60), etc.).
This allows model definitions such as:
```
local lenet = nn.Sequential()
lenet:add(nn.MulConstant(0.00390625))
lenet:add(nn.SpatialConvolution(1,20,5,5,1,1,0)) -- 1*28*28 -> 20*24*24
lenet:add(nn.SpatialMaxPooling(2, 2, 2, 2)) -- 20*24*24 -> 20*12*12
lenet:add(nn.SpatialConvolution(20,50,5,5,1,1,0)) -- 20*12*12 -> 50*8*8
lenet:add(nn.SpatialMaxPooling(2,2,2,2)) --  50*8*8 -> 50*4*4
lenet:add(nn.View(-1):setNumInputDims(3))  -- 50*4*4 -> 800
lenet:add(nn.Linear(800,500))  -- 800 -> 500
lenet:add(nn.ReLU())
lenet:add(nn.Linear(500, 10))  -- 500 -> 10 …
```
> Ignore MulConstant.updateGradInput if self.gradInput is nil

- Normalize.lua
Currently `nn.Normalize` has the following strange behaviour:
```lua
m = nn.Normalize(2)
y = m:forward(torch.randn(3))
> =y
-0.1459
0.8920
-0.4278
[torch.DoubleTensor of size 3]
> = m:forward(torch.randn(3))
0.1877
-0.8429
-0.5043
[torch.DoubleTensor of size 3]
> =y
0.1877 -0.8429 -0.5043
[torch.DoubleTensor of size 1x3]
```
Making it hard to keep track of the output of the module. This PR fixes this.
> Fix modification of output in nn.Normalize

- doc/simple.md
The running results should be as follows:
```
th> model=nn.View(-1):setNumInputDims(2)
[0.0001s]
th> model:forward(input)
0.8104
0.6197
0.0124
0.2712
0.0574
0.6872
[torch.DoubleTensor of size 6]
[0.0002s]
th> input
0.8104  0.6197  0.0124
0.2712  0.0574  0.6872
[torch.DoubleTensor of size 2x3]
[0.0002s]
th> #model:forward(input)
6
[torch.LongStorage of size 1]
```
> wrong example in View

- generic/SpatialConvolutionMM.c
When data size exceeds dozens of GB int variables can’t store data size anymore so memset and memcpy fail with Segmentation fault errors - reproduced when using convolutional neural networks for image processing - in neuralstyle and deepstyle implementation, with images larger than 2000x2000.
You can find that using gdb on lua.
For example [this bug](https://github.com/jcjohnson/neural-style/issues/24) has been closed because of this issue. [This one](https://github.com/kaishengtai/neuralart/issues/11) has not been resolved as well.
> Fixed Segmentation fault on very big data sizes

- Normalize.lua
- test.lua
When `p < 2`, if the input is 0 there was division by zero, as pointed out by @rlebret in https://github.com/torch/nn/issues/440.
Adds a dampening factor `self.eps` to avoid this.
Also, small optimizations for different `p`.
> Fix possible division by zero in Normalize

- CosineDistance.lua
Thanks for the batch version of CosineDistance. Just one quick fix here so it can handle the non-contiguous input. Just for backward-compatibility purpose since the original/old CosineDistance.lua can handle non-contiguous input without problems, and also it is a little bit troublesome for end users to make all input tensors contiguous by themselves. Non-contiguous input cases could happen unfortunately.. for example in this recent [model](http://github.com/hohoCode/textSimilarityConvNet). I tested this fix on my end, it works. 
Thanks again for the batch version update.
> Fix CosineDistance to handle non-contiguous input

- MultiCriterion.lua
- ParallelCriterion.lua
It is not possible to do ```nn.Sequential():add()```, but ```nn.ParallelCriterion():add()``` works without saying anything. Added the asserts.
> asserts in MultiCriterion and ParallelCriterion add

- generic/SpatialConvolutionMM.c
This one will fix the following issue: https://github.com/torch/nn/issues/457 for ix & iy being <0
> Fixed unsigned logic for signed numbers in SpatialConvolutionMM

- generic/SpatialConvolutionMM.c
On Windows (Visual Studio) using 
size_t nip 
results in
error C3016: 'nip' : index variable in OpenMP 'for' statement must have signed integral type
Changed to LONG_PTR nip (LONG_PTR defined in windows.h)
> Win: omp parallel for waits for signed parameter

- Max.lua
- Min.lua
As mentioned by @koraykv in https://github.com/torch/nn/pull/476, `type` method was not updated with `tensorCache`.
I think it doesn't affect sharing etc because those functions doesn't have learnable parameters, but for consistency, it's better to add this `tensorCache` argument.
> Add tensorCache to Min and Max type method

- Normalize.lua
- doc/simple.md
- test.lua
This PR allows normalization by the maximum absolute-value of each batch element.
I thought it would be better to include this functionality into `Normalize`, instead of creating a new function only for that.
Infinity norm can be used by calling the constructor with `math.huge`, as follows
```lua
normalize = nn.Normalize(math.huge)
```
> Normalize supports infinity (maximum) norm

- VolumetricConvolution.lua
- generic/VolumetricConvolutionMM.c
- init.c
- test.lua
**VolumetricConvolution** didn't support ***padding*** before. With this PR ***padding*** can be provided in **VolumetricConvolution** in a way similar to **SpatialConvolution**. That is,
module = nn.VolumetricConvolution(nInputPlane, nOutputPlane, kT, kW, kH, [dT], [dW], [dH], [padT], [padW], [padH])
By default `padT=padW=padH=0`
To be able to add ***padding*** support I had to write a new module to perform Volumetric Convolution, `VolumetricConvolutionMM.c` which, similar to `SpatialConvolutionMM`, constructs Toeplitz matrix and does matrix multiplications. This is done to keep the current implementation of **VolumetricConvolution** intact (`VolumetricConvolution.c`) and it was difficult to add this functionality in it.
I have added necessary test cases in `test.lua`  and …
> Added Padding option in Volumetric convolution

- CosineDistance.lua
- CosineEmbeddingCriterion.lua
Previous version was changing the state variables if not in batch mode, similar issue as the one pointed out in https://github.com/torch/nn/pull/432.
A few notes:
* I'm resizing the state variables `output`, `gradInput`. If you prefer, I can create a temporary buffer instead
* I also cleaned a bit the use of the `buffer` variable. Replacing it by a zero-strided tensor was not a good idea (and lead to the bug mentioned in the bottom of the files), so I just expand it when needed.
> Do not change state variables in CosineDistance/CosineEmbeddingCriterion

- Identity.lua
Fixes #502 by reverting to previous implementation, as the new one had a few unexpected shortcomings.
> Revert to previous Identity.lua implementation

- Parallel.lua
I believe the inherited :size() function was overloaded with the size variable used inside one of the functions. I was not able to use :size() on the Parallel container which is not according to the documentation for the container class.
> fix size for parallel container

- SparseLinear.lua
This is similar to #362, implemented but not used. This is necessary to implement sparse updates correctly. Let me know if there is a reason why this was not included.
> Using sparse implementation of zeroGradParameters for SparseLinear

- SpatialAveragePooling.lua
- doc/convolution.md
- generic/SpatialAveragePooling.c
- test.lua
Generalizes `SpatialAveragePooling` to support free zero padding and ceil mode.
When using padding or ceil mode, the effective number of elements in a region might be different from `kW*kH`. The `:count_exclude_padding()` method considers only the number of elements in the pooling region for the averaging, whereas `:count_include_padding()` always divides by `kW*kH`.
@szagoruyko has a cuda version of this PR.
> SpatialAveragePooling supports padding, ceil mode and more

- Normalize.lua
Remove bmm and baddbmm from Normalize, because they allocate memory, causing sync on CUDA. This version is much faster at least in cutorch.
> Compute Normalize without bmm and baddbmm

- doc/convolution.md
This commit simply adds a greppable note to the docs for `SpatialFullConvolution` to let people find it.
I agree that the terminology used by other frameworks is incorrect (particularly the use of the word "deconvolution"), but this layer is impossible to understand without it. After reading so many papers that refer to "deconvolution" or "upconvolution" layers, I strongly feel that a note like this in the docs is necessary. When I first read the docs for `SpatialFullConvolution`, I thought that it was just convolution with a full connection table since it comes right after the connection-table convolution functions. I wouldn't have ever guessed that this was really deconvolution with a different name.
Other discussions:
https://github.com/torch/nn/pull/405 …
> Add "Deconvolution" note to SpatialFullConvolution docs

- doc/criterion.md
The current docs suggest a sum is computed, but in the code, an average is computed by default. In addition, the order of `o` and `t` for BCE does not match the code.
In addition, added documentation of default behavior of criteria with respect to averaging vs summing of losses.
> Fix docs for BCECriterion and DistKLDivCriterion

- SpatialFullConvolution.lua
- doc/convolution.md
- generic/SpatialFullConvolution.c
- test.lua
There are multiple valid output sizes when using stride that are greater than 1, since there are multiple input sizes that result in the same output size for the regular SpatialConvolution. This term allows the user to control the size of the output by expanding it, up to a value of (stride-1) in each dimension.
> Add adjustment term to SpatialFullConvolution to control output size

- lib/THNN/THNN.h
To fix "implicit declaration of function" warnings.
Note: prior to THNN there was no warning since `SparseLinear.c` already includes `omp.h` (see #286). Now, as soon as sparse linear is moved to THNN there is no need to do [this include](https://github.com/Moodstocks/nn/blob/465c7f1/generic/SparseLinear.c#L5-L7) anymore (cc @andreaskoepf).
> THNN: add missing OpenMP include

- ConcatTable.lua
ConcatTable would throw an error when the inputs were tables of tables of variable length and the length of the second input's elements was smaller than the first's.
e.g.
```lua
in1 = {{torch.randn(5), torch.randn(5)}, torch.randn(5)}
in2 = {{torch.randn(5)}, torch.randn(5)}
c = nn.ConcatTable():add(nn.SelectTable(1)):add(nn.SelectTable(2))
c:forward(in1)
c:backward(in1, in1)
c:forward(in2)
c:backward(in2, in2)
```
returns an "attempt to index a nil value" error on old line 54.
> Fix variable length input bug in concattable

- VolumetricMaxUnpooling.lua
- doc/convolution.md
- generic/VolumetricMaxUnpooling.c
- init.c
- init.lua
- test.lua
Added `Unpooling` option to **VolumetricMaxPooling**. Works with the current `VolumetricMaxPooling` module.
This is the `CPU` version. I will update the `CUDA` version soon.
```lua
require 'nn'
max_module = nn.VoulmetricMaxPooling(kT, kW, kH)
model = nn.Sequential()
model:add(max_module)
model:add(nn.VolumetricMaxUnpooling(max_module))
```
It requires `kT==dT`, `kW==dW`, `kH==dH`.
Updated `init.lua`, `init.c` and `test.lua`.
> Unpooling with stored Indices for Volumetric Max Pool

- Module.lua
Allows modules that want to implement custom `read` and `write` methods to
call `parent.read/write`.
> read and write methods for nn.Module.

- Bilinear.lua
- doc/simple.md
- init.lua
- test.lua
Applies a bilinear transformation to the incoming data, i.e. `\forall k: y_k = x_1 A_k x_2 + b`. The `input` tensor given in `forward(input)` is a table containing both inputs `x_1` and `x_2`, which are tensors of size `N x inputDimension1` and `N x inputDimension1`, respectively. The layer can be trained without biases by setting `bias = false`.
Implemented by @lvdmaaten
> adding a Bilinear layer

- Linear.lua
- doc/simple.md
> add option to nn.Linear to have no bias

- VolumetricMaxPooling.lua
- generic/VolumetricMaxPooling.c
- test.lua
This allows to provide **padding** in `VolumetricMaxPooling`
modified:   VolumetricMaxPooling.lua
modified:   generic/VolumetricMaxPooling.c
modified:   test.lua
**NOTE:** `VolumetricMaxUnpooling` still doesn't support **padded pooling**, though it will work for *pooling module without padding*. I will submit a *patch* for it soon.
> Volumteric Max pooling now supports padding

- VolumetricMaxUnpooling.lua
- doc/convolution.md
- generic/VolumetricMaxUnpooling.c
- test.lua
Patch for `VolumetricMaxUnpooling` to support *padded pooling* introduced [here](https://github.com/torch/nn/pull/589).
Also, updated **README** to reflect `VolumetricMaxPooling` supports *padding*.
modified:   VolumetricMaxUnpooling.lua
modified:   doc/convolution.md
modified:   generic/VolumetricMaxUnpooling.c
modified:   test.lua
> Updated VolumetricMaxUnpooling to support unpooling of padded pooling

- CMul.lua
- utils.lua
Currently, if either the input or gradOuput is non-contiguous, this Module will not work. The change will enable the use of Module in this scenario by performing the necessary tensor copies.
> CMul: Added support for non-contiguous input and gradOuput

- SpatialBatchNormalization.lua
Big oops. I had messed up the backwards compatibility code for SpatialBatchNormalization and my test for this was flawed.
The old-style running_std is actually the E[1/sqrt(var + eps)]. I forgot to subtract out the 'eps' when converting to running_var.
> Fix loading of old SpatialBatchNormalization modules

- Dropout.lua
Initially, the input gradient is not allowed if the dropout layer is not in training mode. However, there shouldn't be anything preventing back propagation. This is useful if we want deterministic behavior with learning model and want to get the derivative with respect to the low input layer.
> Add gradient backprop for dropout in evaluation mode

- VolumetricConvolution.lua
This is a similar issue than the one pointed out in https://github.com/torch/nn/issues/211.
Indeed, the role of `fgradInput` in [the CPU version](https://github.com/torch/nn/blob/master/lib/THNN/generic/VolumetricConvolutionMM.c#L299) is different from [the GPU one](https://github.com/torch/cunn/blob/master/lib/THCUNN/VolumetricConvolution.cu#L208-L213) (which expects only 1s).
> Fix VolumetricConvolution for cpu/gpu interoperability

- BCECriterion.lua
- LogSigmoid.lua
- PReLU.lua
- Reshape.lua
- SpatialAdaptiveMaxPooling.lua
- SpatialConvolution.lua
- SpatialConvolutionLocal.lua
- SpatialConvolutionMM.lua
- SpatialCrossMapLRN.lua
- SpatialFractionalMaxPooling.lua
- SpatialFullConvolution.lua
- SpatialMaxPooling.lua
- TemporalMaxPooling.lua
- VolumetricConvolution.lua
- VolumetricFullConvolution.lua
- VolumetricMaxPooling.lua
- WeightedMSECriterion.lua
For backend switching mostly, see also the discussion here https://github.com/torch/nn/pull/526
> Lazy initialization of buffers

- rocks/nn-scm-1.rockspec
Propagating Lua vars is necessary when compiling with extrenal Lua
> Propagating Lua vars

- SpatialFractionalMaxPooling.lua
:initSampleBuffer_() was producing an error when called (from :updateOutput()) after calling :clearState(). The randomSamples field was an empty tensor in that case.
Now :clearState() sets indices and randomSamples to nil, so the module is in the same state as after construction.
> Fix problem with nn.SpatialFractionalMaxPooling:clearState()

- Reshape.lua
Last commit broke the case when input is continuous and gradOutput is not. This fixes it.
> Reshape: Fixed wrong place of _gradOutput initialization

- Dropout.lua
My previous code has a bug. I fixed it and tested with unit test. The computed gradient agrees with finite difference gradient.
> fixed dropout backprop in evaluation mode

- utils.lua
This means if we have a module which wraps another module, and does
something like:
function MyWrapper:__init(innerModule)
self._innerModule = innerModule
self.gradInput = self._innerModule.gradInput
end
.. Then calling :type before we have forwarded anything (and when we
still have zero-size Tensors) will now correctly preserve this aliasing.
> Make nn.utils.recursiveType add empty Tensors to the tensorCache.

- utils.lua
I'm currently doing some kind of RNN with variable length training.
The current version of recursiveResizeAs(t1, t2) does not erase the contents of the t1 that does not match t2, which leads to error in some cases.
Here is the code to reproduce the error:
```lua
require 'nn'
require 'rnn'
criterion = nn.ParallelCriterion():add(nn.SequencerCriterion(nn.MSECriterion()))
x = torch.randn(1, 10)
y = torch.randn(1, 10)
s1 = {x, x, x, x, x}
s2 = {y, y, y, y, y}
criterion:forward({s1},{s2})
print(criterion:backward({s1},{s2}))
--[[ Output:
{
1 : 
{
1 : DoubleTensor - size: 1x10
2 : DoubleTensor - size: 1x10
3 : DoubleTensor - size: 1x10
4 : DoubleTensor - size: 1x10
5 : DoubleTensor - size: 1x10
}
}
--]]
s1 = {x, x, x}
s2 = {y, y, y}
criterion:forward({s1}, {s2}) …
```
> Remove outdated table items in recursiveResizeAs

- BatchNormalization.lua
- SpatialBatchNormalization.lua
- THNN.lua
- VolumetricBatchNormalization.lua
- init.lua
- lib/THNN/generic/BatchNormalization.c
- lib/THNN/init.c
- test.lua
All of the BatchNormalization modules now extend `nn.BatchNormalization` and use the same THNN/THCUNN implementation.
> Add VolumetricBatchNormalization

- PartialLinear.lua
- doc/simple.md
- init.lua
- test.lua
+ doc + tests
PartialLinear is a Linear layer that allows the user to a set a collection of
column indices. When the column indices are set, the layer will behave like a
Linear layer that only has those columns. Meanwhile, all parameters are
preserved, so resetting the PartialLinear layer will result in a module that
behaves just like a regular Linear layer.
This module is useful, for instance, when you want to do forward-backward on
only a subset of a Linear layer during training but use the full Linear layer
at test time.
Original author: @lvdmaaten
> adding PartialLinear

- Bilinear.lua
- ELU.lua
- Parallel.lua
- Reshape.lua
- SpatialAveragePooling.lua
- SpatialConvolutionLocal.lua
- SpatialConvolutionMM.lua
- SpatialFractionalMaxPooling.lua
- SpatialMaxPooling.lua
- SpatialMaxUnpooling.lua
- SpatialReflectionPadding.lua
- SpatialReplicationPadding.lua
- SpatialZeroPadding.lua
- VolumetricAveragePooling.lua
- VolumetricConvolution.lua
- VolumetricMaxPooling.lua
Better `__tostring()__` for *pooling* modules
Fixing code formatting (Vim took care of that)
> Better __tostring()__ and cleans formatting

- test.lua
These tests (VolumetricConvolution, SpatialConvolutionLocal) could previously take very long (up to several minutes on my machine) and are faster with the new dimensions without sacrificing much generality. The speed-up is roughly from ~1min -> ~10sec for each of these tests.
> Smaller dimensions for several tests

- Jacobian.lua
Some modules, such as LookupTable, don't have gradInput tensors. This
change allows nn.Jacobian.testIO to be called on such modules.
> Fix Jacobian.testIO for modules that don't have gradInput

- Concat.lua
- ConcatTable.lua
- Container.lua
- DepthConcat.lua
- Parallel.lua
- ParallelTable.lua
- Sequential.lua
When an error occurs in some module, all containers up to the topmost one will be printed. This should make network debugging much easier.
Error messages look like this after these changes:
```
/Users/adampaszke/torch/install/bin/luajit:
In nn.Sequential (2):
In nn.Sequential (6):
/Users/adampaszke/torch/install/share/lua/5.1/nn/Linear.lua:55: size mismatch, m1: [1 x 10], m2: [20 x 10] at /Users/adampaszke/torch/pkg/torch/lib/TH/generic/THTensorMath.c:706
stack traceback:
[C]: in function 'error'
.../adampaszke/torch/install/share/lua/5.1/nn/Container.lua:34: in function 'callAndRethrow'
...adampaszke/torch/install/share/lua/5.1/nn/Sequential.lua:45: in function 'forward'
test.lua:21: in main chunk
[C]: in function 'dofile'
...szke/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: …
```
> Improve error handling

- Module.lua
Currently, there is no clear way to get the 'type' of an nn.Module,
although you can set the type via Module:type(<newtype>). This changes
Module:type() to return the current type when called with no arguments.
The module's type is stored in the _type field.
> Add _type field to nn.Module

- .gitignore
- Concat.lua
This is a quick fix for #709. I'll provide regression tests later today, but it's worth fixing it as soon as possible.
Also, added THNN_h.lua to .gitignore.
> Concat fix

- View.lua
Currently, every `forward`/`backward` creates a new tensor (which shares the same storage). 
This PR allows to keep track of the module's `output`/`gradInput`, as the tensor pointers won't change at every forward/backward pass.
I think that this behaviour should be enforced for all `nn` modules. If you agree, I can send a PR fixing this behaviour in other modules.
> View reuses the same internal tensors

- View.lua
> Fix backward-compatibility of nn.View

- L1Penalty.lua
Calling L1Penalty's clearState resulted on an error.
The loss being a scalar, it has no .set method.
```
local loss = m*input:norm(1) 
self.loss = loss  
```
The default Module.clearState should be ok, so I simply removed the L1Penalty's override.
> remove L1Penalty.clearState

- SparseLinear.lua
- lib/THNN/generic/SparseLinear.c
- lib/THNN/generic/THNN.h
- test.lua
updateGradInput has a dense gradInput, so removing that to match LookupTable. We keep a resize for compatibility (with, for example, an nngraph.Identity() node on an input). Fixed the test not to test for gradInput.
Edit: After some discussion I'm redoing SparseLinear:
1. Now supports table inputs, of the format {batch1, batch2, batch3,...} where each batch is an ninput x 2 sparse vector. This lets us input batches of unequal vector sizes
2. UpdateGradInput is now coded correctly to return a dense vector coded in sparse format.
3. UpdateParameters and zeroGradParameters were wrong if we called accGradParameters more than once, because it did sparse updates only on the last input.
The original batchnum x nnz x 2 format is still supported for now...
>  Adding table input support for batched SparseLinear, implementing gradInput correctly, fixing other bugs

- SparseLinear.lua
- lib/THNN/generic/SparseLinear.c
- lib/THNN/generic/THNN.h
- test.lua
See dicussion @ #698 
Speeds up updateGradParameters and zeroGradParameters when one forward/backward update has been run by keeping track of the immediately previous input.
The follow snippet
local nn = require('nn')
local sys = require('sys')
local model = nn.SparseLinear(65536, 256)
local input = torch.rand(5, 2)
input:select(2, 1):mul(65536):ceil()
sys.tic()
local output = model:forward(input)
sys.toc(true)
local gradOutput = torch.rand(output:size())
sys.tic()
local gradInput = model:backward(input, gradOutput)
sys.toc(true)
sys.tic()
model:updateParameters(1e-3)
sys.toc(true)
sys.tic()
model:zeroGradParameters()
sys.toc(true)
gives us
0.00010514259338379	
6.2942504882812e-05	
5.6028366088867e-05	
4.6968460083008e-05
> Sparse Linear now does sparse updates from the last input

- DotProduct.lua
- Max.lua
- Min.lua
- Normalize.lua
- PartialLinear.lua
- Replicate.lua
- Sum.lua
Do not create new `output`/`gradInput` tensors at every function call of `forward`/`backward`, as discussed in https://github.com/torch/nn/pull/712.
`nn.Unsqueeze` is missing in this PR, because we need to change the behaviour of `addSingletonDimension` to accept a result tensor (as done by `torch.view`). Will change both in a separate PR.
> Reuse same state tensors on forward/backward

- doc/criterion.md
The equations on the criterion page are replaced with images of the equations, properly formatted, using online latex-to-image conversion services.  The equations are also made to use more consistent conventions. 
I think this makes some of the more advanced criteria a lot easier to understand.
> Formatted latex equations

- doc/overview.md
The documentation file overview.md has a broken link to `complete list of available modules`. Since no such consolidated list appears in the documentation files, I removed the link. The link may be added back only when we have such a consolidated list of modules in the documentation.
> Removed missing link from documentation

- Container.lua
When using luajit strings have no split method. Fixes error from @fmassa's comment at #682.
> Fix error handling

- Unsqueeze.lua
- test.lua
- utils.lua
Extend `nn.utils.addSingletonDimension` to accept a result tensor as argument.
Add tests for the new case.
> Unsqueeze reuse same state tensors

- VolumetricFullConvolution.lua
Ideally while displaying the *kernel* (and likewise for *padding*, etc.), it should be of the format `kT x kW x kH`, as in the [doc](https://github.com/torch/nn/blob/master/doc/convolution.md#nn.VolumetricFullConvolution) or normal [VolumetricConvolution](https://github.com/kmul00/nn/blob/master/VolumetricConvolution.lua#L184-L194).
Here it was of the format `kW x kH x kT`. This caused confusion to me while creating a model and thought it might to others as well.
> Change display order in VolumetricFullConvolution

- test.lua
For tracking down flaky tests (bugs/timeouts that occur stochastically depending on randomly chosen inputs) I sometimes start tens or hundreds of runs of the tests at once (within a few seconds). Since os.time() has second precision, this usually gives me only very few really different seeds - with torch.tic() many more different seeds can be generated in a short time window.
> Use torch.tic instead of os.time for seeding

- MaskedSelect.lua
- doc/simple.md
- init.lua
- test.lua
Add MaskedSelect module which emulates the bahaviour of torch.Tensor():maskedSelect().
e.g.
```
> ms = nn.MaskedSelect()
> mask = torch.randn(2,2):bernoulli():byte()
> input = torch.randn(2,2)
> =mask
0  0
1  0
[torch.ByteTensor of size 2x2]
> =input
0.6046  1.3675
0.2091 -1.9718
[torch.DoubleTensor of size 2x2]
> out = ms:forward({input, mask})
> =out
0.2091
[torch.DoubleTensor of size 1]
>  gradIn = ms:backward({input, mask}, out)
> =gradIn
{
1 : DoubleTensor - size: 2x2
2 : ByteTensor - size: 2x2
}
> return gradIn[1]
0.0000  0.0000
0.2091  0.0000
[torch.DoubleTensor of size 2x2]
> return gradIn[2]
0  0
0  0
[torch.ByteTensor of size 2x2]
```
> Add MaskedSelect.lua module to replicate torch.maskedSelect behaviour.

- DistKLDivCriterion.lua
In contrast to many other criterions, `DistKLDivCriterion` requires the size of `target` to be the same as that of `input` (for obvious reasons). In case you do this wrong (which can easily happen), there is currently no informative error message but only a failure in the CUDA-code. This diff adds assertions on the `input` and `target` size.
> [DistKLDivCriterion] Add assertions on target size

- Module.lua
Re-created the pull request to see if the flaky builds pass this time.
> Add nil-guard in getParameters, to avoid crashes when there are no parameters

- Module.lua
- doc/module.md
Hi all.
Until now, to change the type of modules sharing parameters, you had to do:
```
m1 = nn.Linear(5,5)
m2 = m1:clone('weight', 'gradWeight')
t = {}
newType = 'torch.CudaTensor'
m1:type(newType, t)
m2:type(newType, t)
```
The following code did not work : 
```
t = {}
m1:cuda(t)
m2:cuda(t)
```
I propose to change the shortcut functions signature so that the previous code work.
Clément.
> add argument passing to module typing shortcuts

- SelectTable.lua
- test.lua
Hi guys,
This PR fixes a bug raised in https://github.com/Element-Research/rnn/issues/204 where the gradInput of SelectTable becomes corrupted when the size of the input table is increased from one forward to the next.
> fix SelectTable variable size gradInput bug

- LookupTable.lua
- doc/convolution.md
- lib/THNN/generic/LookupTable.c
- lib/THNN/generic/THNN.h
- test.lua
Add the ability to this module to have a fixed maximum norm, i.e., no word embedding (a row in the module weight) can have [normValue]-norm > maxNorm (e.g., 2-norm > 1). The constraint is enforced in the forward pass (rows that are accessed are re-normalized), so that the output always obeys the max-norm constraint.
> [LookupTable] Add Max-norm constraints to LookupTable

- BatchNormalization.lua
Hi all,
This assertion is not really necessary and it prevents doing back-propagation to input (computing the derivative of loss w.r.t. the input image).
> delete an assertion in batchnormalization

- SpatialMaxPooling.lua
- SpatialMaxUnpooling.lua
- VolumetricMaxPooling.lua
- VolumetricMaxUnpooling.lua
Doing so breaks deserialization on systems with different architectures (this gives incompatible bytecode error, because the new function has to be serialized with pooling module).
These operations are cheap, so it's not a problem to perform them even when there's no unpooling associated.
> Remove unnecessary function override in unpooling modules

- BatchNormalization.lua
Much needed because CPU version will show a cryptic error and GPU will just proceed with undefined behaviour.
> Add BatchNormalization feature size check

- Jacobian.lua
- Linear.lua
- SpatialConvolution.lua
- SpatialConvolutionMM.lua
- lib/THNN/generic/SpatialConvolutionMM.c
- lib/THNN/generic/THNN.h
- test.lua
Hi,
This is to allow `nn.Linear` and `nn.SpatialConvolution` to have no bias, just like [cudnn.torch](https://github.com/soumith/cudnn.torch).
We can revert https://github.com/soumith/cudnn.torch/pull/164 if this is merged.
@fmassa
> add noBias for nn.Linear and nn.SpatialConvolution

- SparseLinear.lua
Making gradInput an empty table by default in the SparseLinear module.
It's unnecessary to allocate a tensor since updateGradInput will do that if necessary (that is, if in legacy mode).
> SparseLinear: gradInput should be a table by default

- GradientReversal.lua
- doc/simple.md
Added the hyper-parameter lambda for the Gradient Reversal Layer as described in the original paper.
This allows the user to control how much gradient one would like to propagate back to the preceding layers, and it is also possible to set different values for lambda at various stages during training, which is also adopted in the original paper.
> Adding hyper-parameter lambda to GradientReversal module

- Module.lua
- doc/module.md
- test.lua
I think this function should be included in nn.Module functionality. Similar to apply, it is very useful for quick surgeries. I used it for example in cudnn.convert https://github.com/soumith/cudnn.torch/pull/76
Here is a short example:
```lua
require'nn'
local model = nn.Sequential()
model:add(nn.SpatialConvolution(1,96,5,5))
model:add(nn.ReLU())
model:add(nn.SpatialMaxPooling(2,2,2,2))
model:add(nn.SpatialConvolution(96,50,5,5))
model:add(nn.ReLU())
model:add(nn.SpatialMaxPooling(2,2,2,2))
model:add(nn.View(-1):setNumInputDims(3))
model:add(nn.Dropout())
model:add(nn.Linear(800,500))
model:add(nn.ReLU())
model:add(nn.Dropout())
model:add(nn.Linear(500,10))
```
```
nn.Sequential {
(1): nn.SpatialConvolution(1 -> 96, 5x5)
(2): nn.ReLU
(3): nn.SpatialMaxPooling(2,2,2,2)
(4): …
```
> nn.Module.replace

- Select.lua
- test.lua
As nn.SelectTable support negative inputs it seems only natural to also allow nn.Select to support the same.
Just a side note: nn.SelectTable has asserts, should nn.Select have them as well?
I think it's also fine to support this in the Tensor:select function instead.
> nn.Select support for negative indices

- doc/criterion.md
```lua
loss(x, y) = sum_i(max(0, (margin - x[y] + x[i]))^p) / x:size(1)
```
> MultiMarginCriterion description has a typo

- SelectTable.lua
- test.lua
This PR contains 3 things:
* Make `SelectTable` forward pass consistent with the backward wrt to the `index` computation and the assertion. The following sample will now work (it used to fail because in this case `#input == 0`):
```lua
require 'nn'
local mod = nn.SelectTable(5)
local input = {}
input[5] = 2
mod:forward(input)
```
* With the current `test.lua` file, it is not possible to do `luajit test.lua` even though there is some code in there trying do support this. Since `torch7` does not allow this way to run the tests (only calling `torch.test()` from lua is allowed), I removed the associated code here. @soumith if you think we should support this way to run the tests, let me know and I will fix it instead.
* Force the tests to run using only a single thread. This leads to a huge …
> Select table consistency and small test change

- Log.lua
- doc/simple.md
Hi all,
These 2 modules simply add/multiply the input tensor by a constant.  
I was trying to use [dcgan](https://github.com/soumith/dcgan.torch) to generate images that are fed into another model in the pipeline. The problem is that the output of dcgan has to be shifted from `[-1,+1]` to `[0,1]` before further processing. Thus I think simple modules to add/multiply constant might be useful.
> add docs for nn.Log, nn.AddConstant & nn.MulConstant

- SpatialFullConvolution.lua
- VolumetricFullConvolution.lua
- doc/convolution.md
- test.lua
This can used to dynamically set the output size, as an alternative to using the adj terms, which has the downside to be fixed at construction time and makes the output size of these modules depend on the size of the input tensor. This is convenient for conv->rev-conv networks, as the input of the conv can be used as extra input to the rev-conv to go back to the same size exactly.
There is no downside to using the extra input, as there is effectively no gradient flowing back from this input, since this commit in nngraph: https://github.com/torch/nngraph/commit/2c66c0d9ceed8fdfd4f0230a4d0d38f6d9fbcee0
which detects that gradOutput is an expanded zero tensor and skips it.
> Adding an optional extra input to SpatialFull- and VolumetricFull- convolution.

- SplitTable.lua
There are cases when self.gradInput is nil in SplitTable, e.g., when it is the very bottom of the network. A check is necessary to avoid exceptions.
> Add gradInput nil check for SplitTable

- SpatialConvolution.lua
- SpatialConvolutionMM.lua
If you require cutorch and nn but forget cunn and call a module that uses THNN it will throw a non-obvious error `Error attempt to index field 'THNN' (a nil value)` eg https://github.com/soumith/imagenet-multiGPU.torch/issues/69, have seen this issue pop up several times. I added the assert to convolution and convolutionMM, but in general would be good to add this to other modules too.
> add assert to improve error handling

- doc/training.md
I love the quality of the documentation here. Thanks!
One small correction that tripped me up. I was getting:
```
/Users/home/torch/install/bin/luajit: /Users/home/torch/install/share/lua/5.1/nn/THNN.lua:109: bad argument #3 to 'v' (cannot convert 'struct THByteTensor *' to 'struct THDoubleTensor *')
stack traceback:
[C]: in function 'v'
/Users/home/torch/install/share/lua/5.1/nn/THNN.lua:109: in function 'MSECriterion_updateOutput'
/Users/home/torch/install/share/lua/5.1/nn/MSECriterion.lua:14: in function 'forward'
example.lua:42: in function 'opfunc'
/Users/home/torch/install/share/lua/5.1/optim/sgd.lua:44: in function 'sgd'
example.lua:48: in main chunk
[C]: in function 'dofile'
...home/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
[C]: at 0x010088d1f0
```
The …
> Fix optim example to use the correct tensor type for the label

- Narrow.lua
Imagine you would like to chop off ten pixels off of two sides of an image, whose size is unknown. To make this feasible, I changed the Narrow module such that it accepts negative lengths and behaves as follows.
```
th> a = torch.rand(1, 5, 6)
th> a
(1,.,.) = 
0.4982  0.6585  0.4621  0.9703  0.7528  0.6298
0.5106  0.2586  0.6974  0.5139  0.2741  0.0780
0.5161  0.2279  0.6495  0.0238  0.0226  0.7178
0.1969  0.4823  0.2021  0.7990  0.2389  0.1396
0.6029  0.0335  0.0230  0.5429  0.8701  0.8451
[torch.DoubleTensor of size 1x5x6]
th> nn.Narrow(2, 2, -1):forward(a)
(1,.,.) = 
0.5106  0.2586  0.6974  0.5139  0.2741  0.0780
0.5161  0.2279  0.6495  0.0238  0.0226  0.7178
0.1969  0.4823  0.2021  0.7990  0.2389  0.1396
0.6029  0.0335  0.0230  0.5429  0.8701  0.8451
[torch.DoubleTensor of size 1x4x6] …
```
> added support for negative lenghts to Narrow

- VolumetricReplicationPadding.lua
- doc/convolution.md
- init.lua
- lib/THNN/generic/THNN.h
- lib/THNN/generic/VolumetricReplicationPadding.c
- lib/THNN/init.c
- test.lua
This is a simple clone of SpatialReplicationPadding to 3D.
NOTE: we could make SpatialReplicationPadding call this Volumetric implementation (with ``depth = 1`` and ``pfront = pback = 0``), however I was worried about the performance penalty (if anything) of having an unnecessary for loop for the Spatial (2D) version.  The tradeoff is this way we have more code duplication... Thoughts?  I'm happy to remove the SpatialReplicationPadding C code and instead point it to this (more general) version.
CUDA implementation incoming.
> Added VolumetricReplicationPadding.

- lib/THNN/generic/SpatialClassNLLCriterion.c
Although the `b` variable is automatically private, the `elem` loop variable is not private.
Test: change test.lua to run with more than one thread
> Fix SpatialClassNLLCriterion when using OMP

- lib/THNN/generic/ClassNLLCriterion.c
- lib/THNN/generic/SpatialClassNLLCriterion.c
Checks that there are as many weights as classes (before, undefined values could be used).
> NLL Criteria: weight bound checking

- hessian.lua
- lib/THNN/generic/SpatialConvolutionMM.c
- lib/THNN/generic/SpatialDilatedConvolution.c
- lib/THNN/generic/SpatialFullConvolution.c
- lib/THNN/generic/VolumetricConvolutionMM.c
- lib/THNN/generic/VolumetricFullConvolution.c
Very very subtle bugs occur if the BLAS does Y = beta * Y + A*X, even when beta = 0 as opposed to the standard behavior of: Y = A * X
Fix cases for such blas. @clementfarabet ran into these issues as well in the past with nn.Linear, and they do burn you hard...
cc: @apaszke
> memset the result buffers sent into mm (when beta = 0) to zero to fix subtle BLAS behavior based bugs

- doc/convolution.md
add "3D deconvolution" and "3D upsampling" keywords into VolumetricFullConvolution, so that  VolumetricFullConvolution can be easily searched.
> add 3D deconvolution description into VolumetricFullConvolution 

- SpatialFullConvolution.lua
When the input is a `table`, `clearState` will empty `gradInput` by replacing it with an empty table.
This causes the backward pass to fail because `self.gradInput[1]` will be `nil`.
Should I add tests for this particular case in this PR? For the moment there are practically no tests for `clearState`.
> Fix for SpatialFullConvolution for table input after clearState

- LookupTable.lua
nn counterpart for https://github.com/torch/cutorch/pull/461
> fix for cutorch index* changes

- MapTable.lua
- doc/table.md
- init.lua
- test.lua
This module can be useful when dealing with multi-dimensional mini-batches, for
example when training recurrent neural networks (time X batch_size X elements).
It simply clones the contained module as necessary and applies each clone to the
respective input element.
> A container for applying a single module to all table elements

- CMul.lua
- doc/simple.md
- test.lua
This will allow CMul'ing along a particular axis (and without a single `setNumInputDims`!)
```lua
local c = nn.CMul(1, 2, 3, 1)
local t = torch.rand(3, 2, 3, 4)
c:forward(t)
c:backward(t, t)
```
This PR is a possible implementation of the proposal in #910  that maintains backward compatibility, as measured by the tests passing. I'll add tests for this new feature, too, if it's deemed useful!
> Expand CMul weights

- CMaxTable.lua
- CMinTable.lua
- doc/table.md
- init.lua
- test.lua
This is analogous to the other table layers, but only with a max, rather than add or multiply operation. I couldn't think of a good way to implement this to work with arbitrary sized tensors using existing layers, so I thought this might be helpful.
If you think it makes sense to include this feature, I'll add documentation and tests, I just wanted to check whether this feature makes sense before going ahead with that.
Sample usage:
```
th> a = torch.range(1,6):double():resize(3,2)
[0.0003s]	
th> b = torch.Tensor(3,2):fill(3.5):double()
[0.0002s]	
th> a
1  2
3  4
5  6
[torch.DoubleTensor of size 3x2]
[0.0003s]	
th> b
3.5000  3.5000
3.5000  3.5000
3.5000  3.5000
[torch.DoubleTensor of size 3x2]
[0.0003s]	
th> nn.CMaxTable():forward({a,b})
3.5000  3.5000
3.5000  4.0000
5.0000  6.0000 …
```
> add CMaxTable class

- lib/THNN/generic/HardTanh.c
- test.lua
HardTanh does not use inclusive bounds in inplace mode, which makes it
inconsistent with the cuda version, as well as Threshold, ReLU, etc.
Note this doesn't fix torch7 issue #734 (https://github.com/torch/torch7/issues/734), but the inconsistency was causing issues on trivial with tests between the cuda and non-cuda versions of HardTanh.
> HardTanh does not use inclusive bounds in inplace mode

- test.lua
I found these tests to be failing regularly, where the actual values are very small but non-zero.
If you can confirm that this is happening, then this patch makes the tests approximate so they pass most of the time.
> [test.lua] Make i/o forward/backward tests approximate

- ClassNLLCriterion.lua
- SpatialClassNLLCriterion.lua
The changes introduced in commit #979 have broken cutorch/cunn 1.0-0 because there is no `cudaLong` there.  This fix makes the conversion conditional.
An alternative would be to remove the ugly type castings completely, they are not used e.g. in `MultiMarginCriterion` either.
> ClassNLLCriterion broken for cunn1.0-0

- doc/criterion.md
Update documentation: Weights work for ClassNLLCriterion and CrossEntropyCriterion only if sizeAverage is set to false.
> Add weight exception to doc

- Bilinear.lua
[This MWE](https://gist.github.com/adityaramesh/e31f9bafee2a85243f1d4714fd3cb1ff) shows that Bilinear module crashes when `backward` is called after `clearState`. I modified `updateGradInput` in `Bilinear.lua` to repopulate `self.gradInput` after it is emptied by `clearState`. This fixes the crash.
> Fix Bilinear crash when backward is called after clearState.

- SpatialUpSamplingBilinear.lua
- doc/convolution.md
Optionally pass in a table containing output height and width instead of scale.
This is useful when there is no exact integer scale that can produce the required output size. 
```
module = nn.SpatialUpSamplingBilinear(scale)
or
module = nn.SpatialUpSamplingBilinear({oheight=H, owidth=W})
```
> Specify output height and width instead of scale

- PixelShuffle.lua
- doc/simple.md
- init.lua
- test.lua
Added the PixelShuffle layer which rearranges elements in a tensor of shape `[C*r, H, W]` to a tensor of shape `[C, H*r, W*r]`. 
This is useful for implementing efficient sub-pixel convolution with a stride of `1/r`, which can be used for tasks such as super-resolution (see ["Real-Time Single Image and Video Super-Resolution Using an Efficient Sub-Pixel Convolutional Neural Network" - Shi et al.](https://arxiv.org/abs/1609.05158)).
> PixelShuffle module for sub-pixel convolution

- SpatialUpSamplingBilinear.lua
- SpatialUpSamplingNearest.lua
- lib/THNN/generic/SpatialConvolutionLocal.c
- lib/THNN/generic/SpatialConvolutionMM.c
- lib/THNN/generic/SpatialDilatedConvolution.c
- lib/THNN/generic/SpatialDilatedMaxPooling.c
- lib/THNN/generic/SpatialFullConvolution.c
- lib/THNN/generic/SpatialUpSamplingBilinear.c
- lib/THNN/generic/SpatialUpSamplingNearest.c
- lib/THNN/generic/THNN.h
- test.lua
This refactors error checking in all Spatial* modules and adds many more needed shape checks with better error messages.
Found bugs in SpatialUpSamplingBilinear as a result and fixed.
Depends on https://github.com/torch/cunn/pull/353
> more improvments on error messages and shape checks

- CAdd.lua
- test.lua
Hotfix for bug reported [here] (https://github.com/torch/nn/issues/1012#issuecomment-255679397).
Sorry for the large diff, I also converted 4 spaces -> 3 spaces (sorry I missed this in the first PR). The non-whitespace changes are in the `accGradParameters` function, where it now correctly handles the scenario when the input tensor is larger than the `bias` inside of the `CAdd` module. 
Have added a test for this case too.
> hotfix for bug in CAdd

- doc/convolution.md
Fixed a small typo in the output width and height formulas in SpatialDilatedConvolution.
"+" should be a "-"
> Fix output formula in SpatialDilatedConvolution

- lib/THNN/generic/SpatialDilatedConvolution.c
Weight nDimension is checked against 4, then checked against 2 or 4.
> Remove extraneous shape check from SpatialDilatedConvolution.

- SpatialUpSamplingBilinear.lua
- VolumetricConvolution.lua
- lib/THNN/generic/PReLU.c
- lib/THNN/generic/SpatialSubSampling.c
- lib/THNN/generic/TemporalConvolution.c
- lib/THNN/generic/VolumetricConvolutionMM.c
Adds contiguous checking / auto make contiguous code for tests that failed cunn test checking when all parameter tensors were made contiguous.
In some cases we add checking, in some cases we make the tensor contiguous; I did this based on if other tensors in the module were already being made contiguous.
> Contiguous checking

- lib/THNN/generic/LogSoftMax.c
Removed an unnecessary `newContiguous` that was never freed. There's another `newContiguous` on the same tensor several lines below.
> Fix memory leak in LogSoftMax

- lib/THNN/generic/SpatialAveragePooling.c
- lib/THNN/generic/SpatialDilatedMaxPooling.c
There was a problem with `shapeCheck` sometimes when `ceil_mode=True`, as [this part was missing from the size estimates](https://github.com/torch/nn/blob/master/lib/THNN/generic/SpatialDilatedMaxPooling.c#L201-L208).
The following snippet didn't work prior to this change.
```lua
m = nn.SpatialMaxPooling(2,2,2,2,1,1):ceil()
m:forward(torch.rand(1,1,5,5))
m:backward(torch.rand(1,1,5,5),torch.rand(1,1,3,3))
```
with error message
```
Need indices of dimension 4 and indices.size[3] == 4 but got indices to be of shape: [1 x 1 x 3 x 3]
```
The same change should be made in `THCUNN`. I'll send a PR later.
> Fix shapeCheck in Spatial Pooling modules

- doc/convolution.md
According to the implementation, the documentation in TemporalConvolution.md
The parameters of the convolution can be found in self.weight (Tensor of size outputFrameSize x (inputFrameSize x kW))
should be (kW * inputFrameSize).
For a 2D input, the output value of the layer can be precisely described as:
output[t][i] = bias[i]
+ sum_j sum_{k=1}^kW weight[i][j][k]
* input[dW*(t-1)+k)][j]
should be weight[i][k][j]
> fix misleading doc for temporalConvolution.weight

- LookupTable.lua
- SpatialConvolution.lua
- SpatialConvolutionLocal.lua
- SpatialConvolutionMM.lua
- SpatialDilatedConvolution.lua
- SpatialFullConvolution.lua
- VolumetricDilatedConvolution.lua
- VolumetricFullConvolution.lua
- lib/THNN/generic/SpatialConvolutionLocal.c
- lib/THNN/generic/SpatialConvolutionMM.c
- lib/THNN/generic/SpatialDilatedConvolution.c
- lib/THNN/generic/SpatialFullConvolution.c
- lib/THNN/generic/VolumetricDilatedConvolution.c
- lib/THNN/generic/VolumetricFullConvolution.c
Exceptions are:
1) SparseLinear
requires additional parameters to be passed in (e.g. nbatches),
so it's not clear it's worth moving to C since it won't really simplify the binding
code logic.
2) BatchNormalization
requires "makeBatch", which isn't a trivial translation to C.
3) LookupTable
requires "view" in C, which is already a TODO
4) SpatialUpSamplingBilinear
requires "view" in C, which is already TODO
> Move make contiguous code from lua to C.

- BatchNormalization.lua
- SpatialUpSamplingBilinear.lua
- SpatialUpSamplingNearest.lua
These resizes have already been moved to C code in nn/cunn, so are safe to remove.
> Remove resizing of output in lua.

- lib/THNN/generic/SpatialAveragePooling.c
- lib/THNN/generic/SpatialDilatedMaxPooling.c
- lib/THNN/generic/TemporalConvolution.c
- lib/THNN/generic/TemporalMaxPooling.c
- lib/THNN/generic/TemporalSubSampling.c
1) Adds shape checking for Temporal Convolution (this already exists in cunn, but was skipped in nn).
2) Adds gradOutput shape checks for temporal modules
3) Removes unnecessary (too restrictive and/or redundant) shape checks in Spatial Pooling modules.
> Improve fix/shape checks for Temporal and Spatial modules

- SelectTable.lua
- doc/table.md
Allow `nn.SelectTable` to handle `index` of string type.
> SelectTable accept string as key

- Bilinear.lua
- Linear.lua
- LookupTable.lua
- Module.lua
- PartialLinear.lua
- TemporalConvolution.lua
- test/LinearTHNN.lua
Overwriting the `accUpdateGradParameters` field exposed the function to serialization and made the saved object incompatible with other Lua versions.
This could be avoided with a simple conditional branching to call the shared version of this function.
> Avoid function serialization when sharing parameters

- CrossEntropyCriterion.lua
- test.lua
Old behavior to get sizeAverage == false was:
local cri = nn.CrossEntropyCriterion(weights)
cri.nll.sizeAverage = false
which no longer works as nll.sizeAverage is overwritten.  Only overwriting when the value has actually changed preserves the old behavior.
> Preserve old behavior of setting nll.sizeAverage in CrossEntropyCriterion.

- THNN.lua
- lib/THNN/generic/ELU.c
- lib/THNN/generic/HardShrink.c
- lib/THNN/generic/HardTanh.c
- lib/THNN/generic/LeakyReLU.c
- lib/THNN/generic/Linear.c
- lib/THNN/generic/LookupTable.c
- lib/THNN/generic/MarginCriterion.c
- lib/THNN/generic/MultiMarginCriterion.c
- lib/THNN/generic/PReLU.c
- lib/THNN/generic/RReLU.c
- lib/THNN/generic/SoftPlus.c
- lib/THNN/generic/SoftShrink.c
- lib/THNN/generic/SparseLinear.c
- lib/THNN/generic/SpatialConvolutionLocal.c
- lib/THNN/generic/SpatialConvolutionMM.c
- lib/THNN/generic/SpatialConvolutionMap.c
- lib/THNN/generic/SpatialDilatedConvolution.c
- lib/THNN/generic/SpatialFullConvolution.c
- lib/THNN/generic/SpatialFullConvolutionMap.c
- lib/THNN/generic/SpatialSubSampling.c
- lib/THNN/generic/Sqrt.c
- lib/THNN/generic/THNN.h
- lib/THNN/generic/TemporalConvolution.c
- lib/THNN/generic/TemporalSubSampling.c
- lib/THNN/generic/Threshold.c
- lib/THNN/generic/VolumetricConvolution.c
- lib/THNN/generic/VolumetricConvolutionMM.c
- lib/THNN/generic/VolumetricDilatedConvolution.c
- lib/THNN/generic/VolumetricFullConvolution.c
Reverts torch/nn#1109
Backing this out for good measure. See https://github.com/torch/cunn/pull/427 for context
> Revert "Using accreal instead of real in the API"

- CMaxTable.lua
- CMinTable.lua
Since the `Tensor` objects are getting created in the `updateGradInput` function during the backwards calls, to accommodate variable-length tables, we need to make sure that they have the same type as the input tensors.
Sorry I didn't notice this when initially writing the module, and let me know if there are other concerns.
> Make CMaxTable and CMinTable cunn-compatible

- Max.lua
- Min.lua
- Normalize.lua
These modules check the type explicitly for CudaTensor
rather than the regular expression.  There are other
modules that have this identical check, but do operations
on the resulting type which may or may not be supported
(i.e. require more checking), so I didn't change them.
These should be safe because the index type is independent
of the type being checking.
> Support index parameters with Cuda*Tensor.

- AddConstant.lua
- test.lua
Now, `constant_scalar` in `nn.AddConstant` can be a 1-D tensor. It is useful when a fixed bias is needed. And, polished indents.
> Support Tensor constant

- doc/convolution.md
See line 44 of SpatialDilatedConvolution.c
```
long outputHeight = (inputHeight + 2*padH - (dilationH * (kH - 1) + 1)) / dH + 1;
```
The formula in the doc now matches.
> Fix output sizes in dilated convolution docs.

- MultiLabelSoftMarginCriterion.lua
This replaces the earlier MultiLabelSoftMarginCriterion consisting of a Sigmoid, followed by a BCE for loss and gradient computation. The earlier structure led to instability due to numerical precision. 
The new code combines these two steps and uses a more stable form of the loss and gradient.
This addresses issue **https://github.com/torch/nn/issues/949**.
> Use stable loss and gradient for MultiLabelSoftMarginCriterion

- THNN.lua
when THCUNN is loaded.
Both THNN and THCUNN define the accfloat/accdouble typedef via ffi.  The behavior of this seems to be lua version/luajit version dependent (saw test failures with luajit) and it's probably a good idea to get rid of it (as C doesn't let you redefine a typedef in any case).
Since we no longer support 'real' in the header declaration, it makes sense to just define the gsub on accreal; if we want to add back real support we'll have to do something more complicated.
> Remove accreal typedef because it is defined multiple times

- MixtureTable.lua
If batch size between two successive inputs of variable lengths was the same, self.size was not recomputed. I removed all batch size checks to make sure self.size is recomputed every time.
> MixtureTable - variable length bugfix

- Bottle.lua
gradInput is sometimes nil for saving computation (like [this](https://github.com/facebook/fb.resnet.torch/blob/master/models/resnet.lua#L202)). This PR handles this case to avoid error in Bottle.
> Bottle handling gradInput = nil

- doc/criterion.md
The `-` should mathematically be `+`, and it makes it coherent with the math block just before it.
> Fix possible math typo in MultiMarginCriterion doc

- lib/THNN/generic/HardTanh.c
Currently in-place and out-of-place updateGradOutput will produce different results for input=max_val or input=min_val - in-place won't backprop gradient where input=max_val or input=min_val, out-of-place will backprop gradient in this case.
> Fix inconsistent in-place and out-of-place implementations

- Transpose.lua
- doc/simple.md
This PR adds the setNumInputDims() function to nn.Transpose layer. The behaviour is the same as for other layers (e.g. nn.View). It allows the use of minibatches with nn.Transpose
> nn.Transpose setNumInputDims() added

- MapTable.lua
- doc/table.md
- test.lua
These two commits fix a bug in MapTable layer. 
zeroGradParameters only works when parameters are shared among layers. If they are not shared, the call to module:zeroGradParameters() is effective only on the first module. Instead, by calling the parent function, it is effective on the whole set of modules. The same applies for updateParameters.
Since managing a list of shared/not shared parameters is tricky and involves more lines of code, I opted for the simplest solution: a boolean variable that indicates if the whole set of parameters is shared or not. The default behavior remains the same as before.
> MapTable: 'zeroGradParameters' and 'updateParameters' bugfix

- WeightNorm.lua
- test.lua
Both variables can be re-computed from v and g (and gradV/gradG) upon
deserialization.
> WeightNorm: don't serialize weight and gradWeight

- WeightNorm.lua
For layers where the first weight dimension does not correspond to the output
dimension, self.viewOut will *not* correspond to self.weight:size(). This is
fixed by introducing another member variable that simply holds the original size
of the weight matrix.
> Fix WeightNorm serialization for permutated weight matrices

- SelectTable.lua
At present, SelectTable assumes that the tables will contain only tensors. Sometimes it is convenient in NLP work to pass around tables that some tensors and some other other data, such as strings. This fix allows for that, albeit with the caveat that those components of the table will not back-progagate gradients.
> Allow SelectTable to accept non-tensor table content.

- ClassNLLCriterion.lua
- doc/criterion.md
- lib/THNN/generic/ClassNLLCriterion.c
- lib/THNN/generic/THNN.h
- test.lua
Reverts torch/nn#1217
Now that https://github.com/torch/cunn/pull/468 is implemented, this can be merged back again
> Revert "Revert "ClassNLLCriterion supports missing targets""

- Sum.lua
44a15a1 introduced the `squeeze` option for nn.Sum but did not correctly handle the case of serialized nn.Sum modules in which undefined `self.squeeze` means `self.squeeze = true`.
> Fix backward compatibility with serialized nn.Sum modules

- ConcatTable.lua
This prevents bugs from using ConcatTable with LookupTable.
> ConcatTable uses resize instead of resizeAs

- Bilinear.lua
- Container.lua
- DontCast.lua
- FlattenTable.lua
- Identity.lua
- IndexLinear.lua
- SparseLinear.lua
- SpatialFullConvolution.lua
- VolumetricFullConvolution.lua
- hessian.lua
- utils.lua
This allows you to pass custom tensors created with torch.class as parameters.
> parameters() uses torch.type instead of type

- UpSampling.lua
- doc/convolution.md
- init.lua
- lib/THNN/doc/api_reference.md
- test.lua
From issue #1262, a more generic UpSampling module that provides a wrapper to the recently added volumetric upsampling code. Behaves similarly to  the pytorch upsample class, in that it infers 2D or 3D upsampling based on the input size, and can operate in either nearest neighbor or linear mode.
- This module is a little thematically different to the existing upsampling modules, in that it works on either spatial or volumetric depending on the input.
- There is cunn testing code, but I didn't include it as this is an nn commit. I wasn't sure if I could push to two repos at once.
> Added UpSampling module and associated tests.

- BatchNormalization.lua
- test.lua
This fixes a bug where samples of batchsize 1 would introduce a NaN in BatchNormalization.running_var (see C code where `accreal unbiased_var = sum / (n - 1);`). 
Of course, ideally, we wouldn't need to support a batchsize (that is, n) of 1.
But while iterating a dataset of, say, 101 samples in batch sizes of 10 or less, the last batch will have one sample. This use case break BatchNormalization by introducing a NaN in the running_var.
> BN supports batchsize=1
